<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LiteNetLib" Version="2.1.4" />
    <PackageReference Include="MoonSharp" Version="2.0.0" />
  </ItemGroup>
</Project>
