<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Fw.Lua</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../core/cs/Fw.Core.csproj" />
    <PackageReference Include="MoonSharp" Version="2.0.0" />
  </ItemGroup>
</Project>
