using System.Text;
using static BridgeSchema;

static class BridgeCodec
{
    internal static void Stage(GenerationBatch batch, string root, FwConfig config, BridgeModel model)
    {
        GenerateCodecCs(batch, root, config, model);
        GenerateIntentCodecCs(batch, root, config, model);
        GenerateEventCodecCs(batch, root, config, model);
        GeneratePacketCodecCs(batch, root, config, model);
    }

    private static void GenerateCodecCs(GenerationBatch batch, string root, FwConfig config, BridgeModel model)
    {
        var output = config.BridgeCodecCsPath(root);
        var rootNamespace = TextUtil.PascalName(config.ProjectName());
        var text = new StringBuilder();
        text.AppendLine("// @generated by fwgen bridge. Do not edit.");
        text.AppendLine("using System;");
        text.AppendLine("using Godot;");
        text.AppendLine($"using {rootNamespace}.Core;");
        text.AppendLine("using GdArray = Godot.Collections.Array;");
        text.AppendLine("using GdDictionary = Godot.Collections.Dictionary;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Bridge;");
        text.AppendLine();
        text.AppendLine("public static class BridgeCodec");
        text.AppendLine("{");
        text.AppendLine($"    public const int ProtocolVersion = {model.ProtocolVersion};");
        text.AppendLine();
        text.AppendLine("    public static GdDictionary Packet(string type)");
        text.AppendLine("    {");
        text.AppendLine("        var packet = new GdDictionary();");
        text.AppendLine("        packet[BridgeField.Type] = type;");
        text.AppendLine("        packet[BridgeField.ProtocolVersion] = ProtocolVersion;");
        text.AppendLine("        packet[BridgeField.SessionToken] = \"\";");
        text.AppendLine("        return packet;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static string ReadType(GdDictionary packet)");
        text.AppendLine("    {");
        text.AppendLine("        return ReadString(packet, BridgeField.Type);");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static int ReadProtocolVersion(GdDictionary packet)");
        text.AppendLine("    {");
        text.AppendLine("        return ReadInt(packet, BridgeField.ProtocolVersion, 0);");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static bool IsProtocolSupported(GdDictionary packet)");
        text.AppendLine("    {");
        text.AppendLine("        return packet.TryGetValue(BridgeField.ProtocolVersion, out Variant value) && value.VariantType == Variant.Type.Int && value.AsInt64() == ProtocolVersion;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static string ReadSessionToken(GdDictionary packet)");
        text.AppendLine("    {");
        text.AppendLine("        return ReadString(packet, BridgeField.SessionToken);");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static void SetSessionToken(GdDictionary packet, string sessionToken)");
        text.AppendLine("    {");
        text.AppendLine("        packet[BridgeField.SessionToken] = sessionToken;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static string ReadString(GdDictionary packet, string field)");
        text.AppendLine("    {");
        text.AppendLine("        return packet.TryGetValue(field, out Variant value) ? value.AsString() : \"\";");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static string ReadString(GdDictionary packet, string field, string fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return packet.TryGetValue(field, out Variant value) ? value.AsString() : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static bool ReadBool(GdDictionary packet, string field, bool fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return packet.TryGetValue(field, out Variant value) ? value.AsBool() : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        BridgeNumeric.AppendCs(text);
        text.AppendLine("    public static Vector2I ReadVector2I(GdDictionary packet, string field, Vector2I fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return packet.TryGetValue(field, out Variant value) ? value.AsVector2I() : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static bool TryGetDictionary(GdDictionary packet, string field, out GdDictionary value)");
        text.AppendLine("    {");
        text.AppendLine("        value = new GdDictionary();");
        text.AppendLine("        if (!packet.TryGetValue(field, out Variant variant) || variant.VariantType != Variant.Type.Dictionary)");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        value = variant.AsGodotDictionary();");
        text.AppendLine("        return true;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static bool TryGetArray(GdDictionary packet, string field, out GdArray value)");
        text.AppendLine("    {");
        text.AppendLine("        value = new GdArray();");
        text.AppendLine("        if (!packet.TryGetValue(field, out Variant variant) || variant.VariantType != Variant.Type.Array)");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        value = variant.AsGodotArray();");
        text.AppendLine("        return true;");
        text.AppendLine("    }");
        text.AppendLine("}");
        batch.StageText(output, text.ToString());
    }

    private static void GenerateIntentCodecCs(
        GenerationBatch batch,
        string root,
        FwConfig config,
        BridgeModel model
    )
    {
        var schema = model.Schema;
        var output = config.BridgeIntentCodecCsPath(root);
        var intentRoot = model.IntentRoot
            ?? throw new InvalidOperationException("intent.proto has no root message");
        var intentFields = intentRoot.Fields.Where(item => !item.IsOneof).OrderBy(item => item.Number).ToArray();
        var playerIdField = intentFields.FirstOrDefault(field => field.Type == "PlayerId" || field.Name == "player_id");
        var rootNamespace = TextUtil.PascalName(config.ProjectName());
        var text = new StringBuilder();
        text.AppendLine("// @generated by fwgen bridge. Do not edit.");
        text.AppendLine("using System.Collections.Generic;");
        text.AppendLine("using Godot;");
        text.AppendLine($"using {rootNamespace}.Core;");
        text.AppendLine("using GdArray = Godot.Collections.Array;");
        text.AppendLine("using GdDictionary = Godot.Collections.Dictionary;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Bridge;");
        text.AppendLine();
        text.AppendLine("public static class IntentCodec");
        text.AppendLine("{");
        text.AppendLine($"    public static List<{intentRoot.Name}> Decode(GdArray intents)");
        text.AppendLine("    {");
        text.AppendLine($"        var intentsOut = new List<{intentRoot.Name}>();");
        text.AppendLine("        foreach (Variant intent in intents)");
        text.AppendLine("        {");
        text.AppendLine("            if (intent.VariantType != Variant.Type.Dictionary)");
        text.AppendLine("            {");
        text.AppendLine("                continue;");
        text.AppendLine("            }");
        text.AppendLine();
        text.AppendLine("            GdDictionary dict = intent.AsGodotDictionary();");
        var playerIdRead = playerIdField == null
            ? "-1"
            : playerIdField.Type == "PlayerId"
                ? $"BridgeCodec.ReadLong(dict, BridgeField.{Pascal(playerIdField.Name)}, -1)"
                : ReadExpression(schema, "dict", playerIdField);
        text.AppendLine($"            intentsOut.Add(DecodeOne({playerIdRead}, dict));");
        text.AppendLine("        }");
        text.AppendLine("        return intentsOut;");
        text.AppendLine("    }");
        text.AppendLine();
        var playerIdType = playerIdField == null ? "long" : CsIntentType(schema, playerIdField);
        text.AppendLine($"    public static {intentRoot.Name} DecodeOne({playerIdType} playerId, GdDictionary dict)");
        text.AppendLine("    {");
        text.AppendLine($"        return new {intentRoot.Name}(");
        for (var index = 0; index < intentFields.Length; index++)
        {
            var field = intentFields[index];
            var expression = IntentDecodeExpression(schema, field, playerIdField, model.ActionRoot);
            var suffix = index + 1 == intentFields.Length ? "" : ",";
            text.AppendLine($"            {expression}{suffix}");
        }
        text.AppendLine("        );");
        text.AppendLine("    }");
        text.AppendLine();
        RenderInputActionDecoder(text, model, rootNamespace);
        text.AppendLine("}");
        batch.StageText(output, text.ToString());
        batch.StageDelete(Path.Combine(Path.GetDirectoryName(output) ?? root, "_input_codec.cs"));
    }

    private static void RenderInputActionDecoder(StringBuilder text, BridgeModel model, string rootNamespace)
    {
        var schema = model.Schema;
        var actionRoot = model.ActionRoot;
        var intentRoot = model.IntentRoot;
        if (actionRoot == null || intentRoot == null)
        {
            return;
        }
        var actionField = intentRoot.Fields.First(field => field.Type == actionRoot.Name);
        text.AppendLine($"    private static {actionRoot.Name}? DecodeAction(GdDictionary dictionary)");
        text.AppendLine("    {");
        text.AppendLine($"        if (!BridgeCodec.TryGetDictionary(dictionary, BridgeField.{Pascal(actionField.Name)}, out GdDictionary action))");
        text.AppendLine("        {");
        text.AppendLine("            return null;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        string kind = BridgeCodec.ReadString(action, BridgeField.Kind);");
        text.AppendLine("        if (string.IsNullOrEmpty(kind))");
        text.AppendLine("        {");
        text.AppendLine("            return null;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine($"        return new {actionRoot.Name}");
        text.AppendLine("        {");
        text.AppendLine("            Kind = kind,");
        text.AppendLine("            Payload = DecodeActionPayload(kind, action),");
        foreach (var field in model.ActionFields)
        {
            text.AppendLine($"            {Pascal(field.Name)} = {ReadExpression(schema, "action", field)},");
        }
        text.AppendLine("        };");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static object? DecodeActionPayload(string kind, GdDictionary action)");
        text.AppendLine("    {");
        text.AppendLine("        return kind switch");
        text.AppendLine("        {");
        foreach (var variant in actionRoot.Fields.Where(item => item.IsOneof))
        {
            if (!schema.Messages.TryGetValue(variant.Type, out var payload))
            {
                continue;
            }
            text.AppendLine($"            {actionRoot.Name}.{Pascal(variant.Name)} => new global::{rootNamespace}.Core.{payload.Name}");
            text.AppendLine("            {");
            foreach (var field in payload.Fields)
            {
                text.AppendLine($"                {Pascal(field.Name)} = {ReadExpression(schema, "action", field)},");
            }
            text.AppendLine("            },");
        }
        text.AppendLine("            _ => null,");
        text.AppendLine("        };");
        text.AppendLine("    }");
    }

    private static string ReadExpression(ProtoSchema schema, string source, ProtoField field)
    {
        var bridgeField = $"BridgeField.{Pascal(field.Name)}";
        if (BridgeNumeric.IsNumeric(field.Type, schema))
        {
            var method = BridgeNumeric.Method(field.Type);
            return field.IsRepeated
                ? $"BridgeCodec.ReadNumbers({source}, {bridgeField}, BridgeCodec.Require{method})"
                : $"BridgeCodec.Read{method}({source}, {bridgeField})";
        }
        if (field.IsRepeated)
        {
            return $"BridgeCodec.TryGetArray({source}, {bridgeField}, out GdArray {field.Name}Array) ? {field.Name}Array : new GdArray()";
        }
        return field.Type switch
        {
            "string" => $"BridgeCodec.ReadString({source}, {bridgeField})",
            "bool" => $"BridgeCodec.ReadBool({source}, {bridgeField}, false)",
            "Vec2i" => $"BridgeCodec.ReadVector2I({source}, {bridgeField}, Vector2I.Zero)",
            "PlayerId" => $"BridgeCodec.ReadLong({source}, {bridgeField}, {ReadFallback(field)})",
            _ when schema.Enums.ContainsKey(field.Type) => $"BridgeCodec.ReadString({source}, {bridgeField}, {BridgeEnumDefault(schema, field.Type)})",
            _ when IsIntLike(field.Type) => $"BridgeCodec.ReadInt({source}, {bridgeField})",
            _ => $"BridgeCodec.ReadString({source}, {bridgeField})",
        };
    }

    private static string IntentDecodeExpression(
        ProtoSchema schema,
        ProtoField field,
        ProtoField? playerIdField,
        ProtoMessage? actionRoot
    )
    {
        if (playerIdField != null && field.Name == playerIdField.Name)
        {
            return "playerId";
        }
        if (actionRoot != null && field.Type == actionRoot.Name)
        {
            return "DecodeAction(dict)";
        }
        if (field.Name == "client_tick" && field.Type == "uint32")
        {
            return $"BridgeCodec.ReadUInt(dict, BridgeField.{Pascal(field.Name)})";
        }
        return ReadExpression(schema, "dict", field);
    }

    private static string ReadFallback(ProtoField field)
    {
        _ = field;
        return "0";
    }

    private static void GenerateEventCodecCs(
        GenerationBatch batch,
        string root,
        FwConfig config,
        BridgeModel model
    )
    {
        var schema = model.Schema;
        var output = config.BridgeEventCodecCsPath(root);
        var eventRoot = model.EventRoot
            ?? throw new InvalidOperationException("event.proto has no oneof root message");
        var eventTypeName = RuntimeEventType(eventRoot);
        var rootNamespace = TextUtil.PascalName(config.ProjectName());
        var text = new StringBuilder();
        text.AppendLine("// @generated by fwgen bridge. Do not edit.");
        text.AppendLine("using System.Collections.Generic;");
        text.AppendLine("using Godot;");
        text.AppendLine($"using {rootNamespace}.Core;");
        text.AppendLine("using GdArray = Godot.Collections.Array;");
        text.AppendLine("using GdDictionary = Godot.Collections.Dictionary;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Bridge;");
        text.AppendLine();
        text.AppendLine("public static class EventCodec");
        text.AppendLine("{");
        text.AppendLine($"    public static GdArray Encode(IReadOnlyList<{eventTypeName}> events)");
        text.AppendLine("    {");
        text.AppendLine("        var output = new GdArray();");
        text.AppendLine($"        foreach ({eventTypeName} ev in events)");
        text.AppendLine("        {");
        text.AppendLine("            output.Add(EncodeOne(ev));");
        text.AppendLine("        }");
        text.AppendLine("        return output;");
        text.AppendLine("    }");
        text.AppendLine();
        RenderEventEncoder(text, model, rootNamespace);
        text.AppendLine("}");
        batch.StageText(output, text.ToString());
    }

    private static void GeneratePacketCodecCs(
        GenerationBatch batch,
        string root,
        FwConfig config,
        BridgeModel model
    )
    {
        var schema = model.Schema;
        var output = config.BridgePacketCodecCsPath(root);
        var rootNamespace = TextUtil.PascalName(config.ProjectName());
        var text = new StringBuilder();
        text.AppendLine("// @generated by fwgen bridge. Do not edit.");
        text.AppendLine("using Godot;");
        text.AppendLine($"using {rootNamespace}.Core;");
        text.AppendLine("using GdArray = Godot.Collections.Array;");
        text.AppendLine("using GdDictionary = Godot.Collections.Dictionary;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Bridge;");
        text.AppendLine();
        text.AppendLine("public static class PacketCodec");
        text.AppendLine("{");

        foreach (var payload in model.PacketPayloads)
        {
            RenderPacketCreator(text, schema, payload);
            text.AppendLine();
        }

        foreach (var payload in model.PacketPayloads)
        {
            RenderPacketReader(text, schema, payload);
            text.AppendLine();
        }

        text.AppendLine("    private static GdDictionary Payload(string field, Variant value)");
        text.AppendLine("    {");
        text.AppendLine("        var payload = new GdDictionary();");
        text.AppendLine("        payload[field] = value;");
        text.AppendLine("        return payload;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static bool TryPayload(GdDictionary packet, string type, string field, out GdDictionary payload)");
        text.AppendLine("    {");
        text.AppendLine("        payload = new GdDictionary();");
        text.AppendLine("        if (!BridgeCodec.IsProtocolSupported(packet) || BridgeCodec.ReadType(packet) != type)");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");
        text.AppendLine("        return BridgeCodec.TryGetDictionary(packet, field, out payload);");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static bool TryReadString(GdDictionary packet, string field, out string value)");
        text.AppendLine("    {");
        text.AppendLine("        value = \"\";");
        text.AppendLine("        if (!packet.TryGetValue(field, out Variant variant))");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");
        text.AppendLine("        value = variant.AsString();");
        text.AppendLine("        return true;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static bool TryReadBool(GdDictionary packet, string field, out bool value)");
        text.AppendLine("    {");
        text.AppendLine("        value = false;");
        text.AppendLine("        if (!packet.TryGetValue(field, out Variant variant))");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");
        text.AppendLine("        value = variant.AsBool();");
        text.AppendLine("        return true;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static bool TryReadFloat(GdDictionary packet, string field, out float value)");
        text.AppendLine("    {");
        text.AppendLine("        return BridgeCodec.TryReadNumber(packet, field, BridgeCodec.RequireFloat, out value);");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static bool TryReadVector2I(GdDictionary packet, string field, out Vector2I value)");
        text.AppendLine("    {");
        text.AppendLine("        value = Vector2I.Zero;");
        text.AppendLine("        if (!packet.TryGetValue(field, out Variant variant) || variant.VariantType != Variant.Type.Vector2I)");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");
        text.AppendLine("        value = variant.AsVector2I();");
        text.AppendLine("        return true;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static bool TryReadLong(GdDictionary packet, string field, out long value)");
        text.AppendLine("    {");
        text.AppendLine("        return BridgeCodec.TryReadNumber(packet, field, BridgeCodec.RequireLong, out value);");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static bool TryReadInt(GdDictionary packet, string field, out int value)");
        text.AppendLine("    {");
        text.AppendLine("        return BridgeCodec.TryReadNumber(packet, field, BridgeCodec.RequireInt, out value);");
        text.AppendLine("    }");
        text.AppendLine("}");
        batch.StageText(output, text.ToString());
    }

    private static void RenderPacketCreator(StringBuilder text, ProtoSchema schema, ProtoField payload)
    {
        var methodName = Pascal(payload.Name);
        var packetType = $"BridgePacketType.{methodName}";
        var payloadField = $"BridgeField.{methodName}";
        var payloadMessage = schema.Messages.TryGetValue(payload.Type, out var message)
            ? message
            : new ProtoMessage(payload.Type, "");
        var args = payloadMessage.Fields
            .Select(field => $"{PacketRuntimeType(schema, field)} {Camel(field.Name)}")
            .ToArray();

        text.AppendLine($"    public static GdDictionary {methodName}({string.Join(", ", args)})");
        text.AppendLine("    {");
        text.AppendLine($"        var packet = BridgeCodec.Packet({packetType});");
        if (payloadMessage.Fields.Count == 0)
        {
            text.AppendLine($"        packet[{payloadField}] = new GdDictionary();");
        }
        else if (payloadMessage.Fields.Count == 1)
        {
            var field = payloadMessage.Fields[0];
            text.AppendLine($"        packet[{payloadField}] = Payload(BridgeField.{Pascal(field.Name)}, {PacketEncodeExpression(schema, field, Camel(field.Name))});");
        }
        else
        {
            text.AppendLine("        var payload = new GdDictionary();");
            foreach (var field in payloadMessage.Fields)
            {
                text.AppendLine($"        payload[BridgeField.{Pascal(field.Name)}] = {PacketEncodeExpression(schema, field, Camel(field.Name))};");
            }
            text.AppendLine($"        packet[{payloadField}] = payload;");
        }
        text.AppendLine("        return packet;");
        text.AppendLine("    }");
    }

    private static void RenderPacketReader(StringBuilder text, ProtoSchema schema, ProtoField payload)
    {
        var methodName = Pascal(payload.Name);
        var packetType = $"BridgePacketType.{methodName}";
        var payloadField = $"BridgeField.{methodName}";
        var payloadMessage = schema.Messages.TryGetValue(payload.Type, out var message)
            ? message
            : new ProtoMessage(payload.Type, "");

        if (payloadMessage.Fields.Count == 0)
        {
            text.AppendLine($"    public static bool TryRead{methodName}(GdDictionary packet)");
            text.AppendLine("    {");
            text.AppendLine($"        return TryPayload(packet, {packetType}, {payloadField}, out _);");
            text.AppendLine("    }");
            return;
        }

        var args = payloadMessage.Fields
            .Select(field => $"out {PacketRuntimeType(schema, field)} {Camel(field.Name)}")
            .ToArray();
        text.AppendLine($"    public static bool TryRead{methodName}(GdDictionary packet, {string.Join(", ", args)})");
        text.AppendLine("    {");
        foreach (var field in payloadMessage.Fields)
        {
            text.AppendLine($"        {Camel(field.Name)} = {PacketDefaultValue(schema, field)};");
        }
        text.AppendLine($"        if (!TryPayload(packet, {packetType}, {payloadField}, out GdDictionary payload))");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");

        if (payloadMessage.Fields.Count == 1)
        {
            var field = payloadMessage.Fields[0];
            text.AppendLine($"        return {PacketReadExpression(schema, field)};");
        }
        else
        {
            text.AppendLine("        var ok = true;");
            foreach (var field in payloadMessage.Fields)
            {
                text.AppendLine($"        ok &= {PacketReadExpression(schema, field)};");
            }
            text.AppendLine("        return ok;");
        }
        text.AppendLine("    }");
    }

    private static string PacketRuntimeType(ProtoSchema schema, ProtoField field)
    {
        if (field.IsRepeated)
        {
            return "GdArray";
        }
        if (BridgeNumeric.IsNumeric(field.Type, schema)) return CsCoreType(schema, field.Type, false);
        return field.Type switch
        {
            "string" => "string",
            "bool" => "bool",
            "float" or "double" => "float",
            "Vec2i" => "Vector2I",
            "PlayerId" => "long",
            "EntityId" => "int",
            _ when schema.Enums.ContainsKey(field.Type) => "string",
            _ when IsIntLike(field.Type) => "int",
            _ => "GdDictionary",
        };
    }

    private static string PacketDefaultValue(ProtoSchema schema, ProtoField field)
    {
        if (field.IsRepeated)
        {
            return "new GdArray()";
        }
        return field.Type switch
        {
            "string" => "\"\"",
            "bool" => "false",
            "float" or "double" => "0.0f",
            "Vec2i" => "Vector2I.Zero",
            "PlayerId" => "0",
            "EntityId" => "0",
            _ when schema.Enums.ContainsKey(field.Type) => BridgeEnumDefault(schema, field.Type),
            _ when IsIntLike(field.Type) => "0",
            _ => "new GdDictionary()",
        };
    }

    private static string PacketReadExpression(ProtoSchema schema, ProtoField field)
    {
        var variable = Camel(field.Name);
        var bridgeField = $"BridgeField.{Pascal(field.Name)}";
        if (BridgeNumeric.IsNumeric(field.Type, schema))
        {
            var method = BridgeNumeric.Method(field.Type);
            var read = field.IsRepeated
                ? $"raw => BridgeCodec.RequireNumberArray(raw, value => BridgeCodec.Encode{method}(BridgeCodec.Require{method}(value)))"
                : $"BridgeCodec.Require{method}";
            return $"BridgeCodec.TryReadNumber(payload, {bridgeField}, {read}, out {variable})";
        }
        if (field.IsRepeated)
        {
            return $"BridgeCodec.TryGetArray(payload, {bridgeField}, out {variable})";
        }
        return field.Type switch
        {
            "string" => $"TryReadString(payload, {bridgeField}, out {variable})",
            "bool" => $"TryReadBool(payload, {bridgeField}, out {variable})",
            "float" or "double" => $"TryReadFloat(payload, {bridgeField}, out {variable})",
            "Vec2i" => $"TryReadVector2I(payload, {bridgeField}, out {variable})",
            "PlayerId" => $"TryReadLong(payload, {bridgeField}, out {variable})",
            "EntityId" => $"TryReadInt(payload, {bridgeField}, out {variable})",
            _ when schema.Enums.ContainsKey(field.Type) => $"TryReadString(payload, {bridgeField}, out {variable})",
            _ when IsIntLike(field.Type) => $"TryReadInt(payload, {bridgeField}, out {variable})",
            _ => $"BridgeCodec.TryGetDictionary(payload, {bridgeField}, out {variable})",
        };
    }

    private static void RenderEventEncoder(StringBuilder text, BridgeModel model, string rootNamespace)
    {
        var schema = model.Schema;
        var eventRoot = model.EventRoot
            ?? throw new InvalidOperationException("event.proto has no oneof root message");
        var eventTypeName = RuntimeEventType(eventRoot);
        text.AppendLine($"    private static GdDictionary EncodeOne({eventTypeName} ev)");
        text.AppendLine("    {");
        text.AppendLine("        var data = new GdDictionary();");
        text.AppendLine("        data[BridgeField.Type] = ev.Type;");
        text.AppendLine("        switch (ev.Type)");
        text.AppendLine("        {");
        foreach (var variant in eventRoot.Fields.Where(item => item.IsOneof))
        {
            if (!schema.Messages.TryGetValue(variant.Type, out var message))
            {
                continue;
            }
            text.AppendLine($"            case {eventTypeName}.{ClassNameForEvent(variant.Type)}:");
            foreach (var field in message.Fields)
            {
                var typedName = $"typed{ClassNameForEvent(variant.Type)}{Pascal(field.Name)}";
                var fallback = $"ev.{Pascal(field.Name)}";
                var aggregate = model.EventFields.Single(item => item.Name == field.Name);
                if (BridgeNumeric.IsNumeric(field.Type, schema) && aggregate.Type != field.Type)
                {
                    var itemType = CsCoreType(schema, field.Type, false);
                    var scalar = aggregate.Type == "__bridge_integer"
                        ? $"BridgeCodec.RequireIntegerUnionValue({(field.IsRepeated ? "value" : fallback)})"
                        : field.IsRepeated ? "value" : fallback;
                    fallback = field.IsRepeated
                        ? $"global::System.Linq.Enumerable.Select({fallback}, value => checked(({itemType}){scalar}))"
                        : $"checked(({itemType}){scalar})";
                }
                text.AppendLine(
                    $"                data[BridgeField.{Pascal(field.Name)}] = ev.Payload is global::{rootNamespace}.Core.{message.Name} {typedName} ? {EventEncodeExpression(schema, field, $"{typedName}.{Pascal(field.Name)}")} : {EventEncodeExpression(schema, field, fallback)};"
                );
            }
            text.AppendLine("                break;");
        }
        text.AppendLine("        }");
        text.AppendLine("        return data;");
        text.AppendLine("    }");
    }

    private static string PacketEncodeExpression(ProtoSchema schema, ProtoField field, string value)
    {
        if (!BridgeNumeric.IsNumeric(field.Type, schema)) return value;
        var method = BridgeNumeric.Method(field.Type);
        return field.IsRepeated
            ? $"BridgeCodec.RequireNumbers({value}, value => BridgeCodec.Encode{method}(BridgeCodec.Require{method}(value)))"
            : $"BridgeCodec.Encode{method}({value})";
    }

    private static string EventEncodeExpression(ProtoSchema schema, ProtoField field, string value)
    {
        if (!BridgeNumeric.IsNumeric(field.Type, schema)) return value;
        var method = BridgeNumeric.Method(field.Type);
        return field.IsRepeated
            ? $"BridgeCodec.EncodeNumbers({value}, BridgeCodec.Encode{method})"
            : $"BridgeCodec.Encode{method}({value})";
    }

}
