using System.Text;
using static BridgeSchema;

static class BridgeTypes
{
    internal static void Stage(GenerationBatch batch, string root, FwConfig config, BridgeModel model)
    {
        var schema = model.Schema;
        var output = config.BridgeTypesCsPath(root);
        var rootNamespace = TextUtil.PascalName(config.ProjectName());
        var text = new StringBuilder();
        text.AppendLine("// @generated by fwgen bridge. Do not edit.");
        text.AppendLine("using System.Collections.Generic;");
        if (schema.Messages.Values.SelectMany(item => item.Fields).Any(item => item.Type == "Vec2i"))
        {
            text.AppendLine("using Godot;");
        }
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Core;");
        text.AppendLine();
        RenderBridgeFields(text, model);
        text.AppendLine();
        RenderBridgeEnums(text, model);
        text.AppendLine();
        RenderPacketTypes(text, model);
        text.AppendLine();
        RenderOneofPayloadTypes(text, schema, model.ActionRoot);
        text.AppendLine();
        RenderActionCs(text, model);
        text.AppendLine();
        RenderIntentCs(text, model);
        text.AppendLine();
        RenderOneofPayloadTypes(text, schema, model.EventRoot);
        text.AppendLine();
        RenderCoreEventCs(text, model);
        batch.StageText(output, text.ToString());
    }

    private static void RenderBridgeFields(StringBuilder text, BridgeModel model)
    {
        text.AppendLine("public static class BridgeField");
        text.AppendLine("{");
        foreach (var field in model.FieldNames)
        {
            text.AppendLine($"    public const string {Pascal(field)} = \"{field}\";");
        }
        text.AppendLine("}");
    }

    private static void RenderBridgeEnums(StringBuilder text, BridgeModel model)
    {
        var renderedAny = false;
        foreach (var protoEnum in model.ValueEnums)
        {
            if (renderedAny)
            {
                text.AppendLine();
            }
            RenderStringEnum(text, protoEnum, BridgeEnumClass(protoEnum.Name));
            renderedAny = true;
        }

        var buttonEnum = model.ButtonEnum;
        if (buttonEnum != null)
        {
            if (renderedAny)
            {
                text.AppendLine();
            }
            RenderButtonEnum(text, buttonEnum);
        }
    }

    private static void RenderPacketTypes(StringBuilder text, BridgeModel model)
    {
        text.AppendLine("public static class BridgePacketType");
        text.AppendLine("{");
        var protoEnum = model.PacketEnum;
        if (protoEnum != null)
        {
            foreach (var value in protoEnum.Values.Where(item => item.Number != 0))
            {
                var name = PacketValueName(value.Name);
                text.AppendLine($"    public const string {Pascal(name)} = \"{name}\";");
            }
        }
        text.AppendLine("}");
    }

    private static void RenderStringEnum(StringBuilder text, ProtoEnum protoEnum, string className)
    {
        text.AppendLine($"public static class {className}");
        text.AppendLine("{");
        foreach (var value in protoEnum.Values.Where(item => item.Number != 0))
        {
            var name = EnumTail(value.Name);
            text.AppendLine($"    public const string {Pascal(name)} = \"{Pascal(name)}\";");
        }
        text.AppendLine("}");
    }

    private static void RenderButtonEnum(StringBuilder text, ProtoEnum protoEnum)
    {
        text.AppendLine("public static class BridgeButton");
        text.AppendLine("{");
        foreach (var value in protoEnum.Values.Where(item => item.Number != 0))
        {
            text.AppendLine($"    public const int {Pascal(EnumTail(value.Name))} = {value.Number};");
        }
        text.AppendLine("}");
    }

    private static void RenderOneofPayloadTypes(
        StringBuilder text,
        ProtoSchema schema,
        ProtoMessage? root
    )
    {
        if (root == null)
        {
            return;
        }
        var first = true;
        foreach (var variant in root.Fields.Where(item => item.IsOneof))
        {
            if (!schema.Messages.TryGetValue(variant.Type, out var payload))
            {
                continue;
            }
            if (!first)
            {
                text.AppendLine();
            }
            first = false;
            text.AppendLine($"public sealed class {payload.Name}");
            text.AppendLine("{");
            foreach (var field in payload.Fields)
            {
                var init = CsDefaultInit(schema, field);
                text.AppendLine($"    public {CsCoreType(schema, field.Type, field.IsRepeated)} {Pascal(field.Name)} {{ get; init; }}{init}");
            }
            text.AppendLine("}");
        }
    }

    private static void RenderActionCs(StringBuilder text, BridgeModel model)
    {
        var schema = model.Schema;
        var actionRoot = model.ActionRoot;
        if (actionRoot == null)
        {
            return;
        }
        text.AppendLine($"public sealed class {actionRoot.Name}");
        text.AppendLine("{");
        foreach (var variant in actionRoot.Fields.Where(item => item.IsOneof))
        {
            text.AppendLine($"    public const string {Pascal(variant.Name)} = \"{variant.Name}\";");
        }

        var fields = model.ActionFields;
        text.AppendLine();
        text.AppendLine("    public string Kind { get; init; } = \"\";");
        text.AppendLine("    public object? Payload { get; init; }");
        text.AppendLine("    public T? As<T>() where T : class => Payload as T;");
        foreach (var field in fields)
        {
            var init = CsDefaultInit(schema, field);
            text.AppendLine($"    public {CsCoreType(schema, field.Type, field.IsRepeated)} {Pascal(field.Name)} {{ get; init; }}{init}");
        }
        text.AppendLine("}");
    }

    private static void RenderIntentCs(StringBuilder text, BridgeModel model)
    {
        var schema = model.Schema;
        var intentRoot = model.IntentRoot;
        if (intentRoot == null)
        {
            return;
        }
        var fields = intentRoot.Fields.Where(item => !item.IsOneof).OrderBy(item => item.Number).ToArray();
        var buttonEnum = model.ButtonEnum;
        text.AppendLine($"public readonly struct {intentRoot.Name}");
        text.AppendLine("{");
        if (buttonEnum != null)
        {
            foreach (var value in buttonEnum.Values.Where(item => item.Number != 0))
            {
                var name = Pascal(EnumTail(value.Name));
                text.AppendLine($"    public const int Btn{name} = BridgeButton.{name};");
            }
            text.AppendLine();
        }
        text.AppendLine($"    public {intentRoot.Name}(");
        for (var index = 0; index < fields.Length; index++)
        {
            var field = fields[index];
            var suffix = index + 1 == fields.Length ? "" : ",";
            text.AppendLine($"        {CsIntentType(schema, field)} {Camel(IntentPropertyName(field))}{suffix}");
        }
        text.AppendLine("    )");
        text.AppendLine("    {");
        foreach (var field in fields)
        {
            var property = IntentPropertyName(field);
            text.AppendLine($"        {property} = {Camel(property)};");
        }
        text.AppendLine("    }");
        text.AppendLine();
        foreach (var field in fields)
        {
            text.AppendLine($"    public {CsIntentType(schema, field)} {IntentPropertyName(field)} {{ get; }}");
        }
        var properties = fields.Select(IntentPropertyName).ToHashSet(StringComparer.Ordinal);
        if (properties.Contains("Hold") && properties.Contains("Down") && properties.Contains("Up"))
        {
            text.AppendLine();
            foreach (var name in new[] { "Hold", "Down", "Up" })
            {
                var field = fields.Single(item => IntentPropertyName(item) == name);
                text.AppendLine($"    public bool Is{name}(int mask) => ({name} & unchecked(({CsIntentType(schema, field)})mask)) != 0;");
            }
        }
        text.AppendLine("}");
    }

    private static void RenderCoreEventCs(StringBuilder text, BridgeModel model)
    {
        var schema = model.Schema;
        var eventRoot = model.EventRoot;
        if (eventRoot == null)
        {
            return;
        }
        var eventTypeName = RuntimeEventType(eventRoot);
        text.AppendLine($"public sealed class {eventTypeName}");
        text.AppendLine("{");
        foreach (var variant in eventRoot.Fields.Where(item => item.IsOneof))
        {
            text.AppendLine($"    public const string {ClassNameForEvent(variant.Type)} = \"{ClassNameForEvent(variant.Type)}\";");
        }

        var fields = model.EventFields;
        text.AppendLine();
        text.AppendLine("    public string Type { get; init; } = \"\";");
        text.AppendLine("    public object? Payload { get; init; }");
        text.AppendLine("    public T? As<T>() where T : class => Payload as T;");
        foreach (var field in fields)
        {
            var init = CsDefaultInit(schema, field);
            text.AppendLine($"    public {CsCoreType(schema, field.Type, field.IsRepeated)} {Pascal(field.Name)} {{ get; init; }}{init}");
        }
        text.AppendLine("}");
    }
}
