using System.Text;
using static BridgeSchema;

static class BridgeGd
{
    internal static void Stage(GenerationBatch batch, string gdDir, BridgeModel model)
    {
        var text = new StringBuilder();
        text.AppendLine("# This file is generated by fwgen. Do not edit manually.");
        text.AppendLine("extends RefCounted");
        text.AppendLine("class_name Bridge");
        text.AppendLine();
        text.AppendLine(BridgeNumeric.GdHelpers());
        text.Append(RenderGdValue(model));
        text.AppendLine();
        text.Append(RenderGdIntent(model));
        text.AppendLine();
        text.Append(RenderGdEvent(model));
        text.AppendLine();
        text.Append(RenderGdView(model));
        text.AppendLine();
        text.Append(RenderGdPacket(model));

        batch.StageText(Path.Combine(gdDir, "_bridge.gd"), text.ToString());
        DeleteLegacyGd(batch, gdDir);
    }

    private static void DeleteLegacyGd(GenerationBatch batch, string gdDir)
    {
        foreach (var name in new[]
        {
            "_action.gd",
            "_action.gd.uid",
            "_input.gd",
            "_input.gd.uid",
            "_event.gd",
            "_event.gd.uid",
            "_snapshot.gd",
            "_snapshot.gd.uid",
            "_view.gd",
            "_view.gd.uid",
        })
        {
            batch.StageDelete(Path.Combine(gdDir, name));
        }
    }

    private static string RenderGdValue(BridgeModel model)
    {
        var text = new StringBuilder();
        text.AppendLine("class Value:");
        text.AppendLine("\textends RefCounted");
        foreach (var protoEnum in model.ValueEnums)
        {
            RenderGdStringEnum(text, protoEnum);
        }
        return text.ToString();
    }

    private static void RenderGdStringEnum(StringBuilder text, ProtoEnum protoEnum)
    {
        text.AppendLine();
        text.AppendLine($"\tclass {protoEnum.Name}:");
        text.AppendLine("\t\textends RefCounted");
        foreach (var value in protoEnum.Values.Where(item => item.Number != 0))
        {
            var name = EnumTail(value.Name);
            text.AppendLine($"\t\tconst {GdConstName(name)} := \"{Pascal(name)}\"");
        }
    }

    private static string RenderGdIntent(BridgeModel model)
    {
        var schema = model.Schema;
        var text = new StringBuilder();
        text.AppendLine("class Intent:");
        text.AppendLine("\textends RefCounted");
        var buttons = model.ButtonEnum;
        if (buttons != null)
        {
            foreach (var value in buttons.Values.Where(item => item.Number != 0))
            {
                text.AppendLine($"\tconst BTN_{EnumTail(value.Name).ToUpperInvariant()} := {value.Number}");
            }
        }
        var actionRoot = model.ActionRoot;
        if (actionRoot == null)
        {
            return text.ToString();
        }

        foreach (var variant in actionRoot.Fields.Where(item => item.IsOneof))
        {
            if (!schema.Messages.TryGetValue(variant.Type, out var action))
            {
                continue;
            }

            text.AppendLine();
            var args = action.Fields.Select(item => $"{item.Name}: {GdArgType(schema, item)}");
            text.AppendLine($"\tstatic func {variant.Name}({string.Join(", ", args)}) -> Dictionary:");
            foreach (var field in action.Fields.Where(field => BridgeNumeric.IsNumeric(field.Type, schema)))
            {
                text.AppendLine($"\t\tif not Bridge.Numeric.valid({field.Name}, \"{field.Type}\", \"{field.Name}\", {field.IsRepeated.ToString().ToLowerInvariant()}):");
                text.AppendLine("\t\t\treturn {}");
            }
            text.AppendLine("\t\treturn {");
            text.AppendLine($"\t\t\t\"kind\": \"{variant.Name}\",");
            foreach (var field in action.Fields)
            {
                var value = BridgeNumeric.IsNumeric(field.Type, schema)
                    ? $"Bridge.Numeric.{(field.IsRepeated ? "read_array" : "read")}({field.Name}, \"{field.Type}\", \"{field.Name}\")"
                    : field.Name;
                text.AppendLine($"\t\t\t\"{field.Name}\": {value},");
            }
            text.AppendLine("\t\t}");
        }
        return text.ToString();
    }

    private static string RenderGdPacket(BridgeModel model)
    {
        var text = new StringBuilder();
        text.AppendLine("class Packet:");
        text.AppendLine("\textends RefCounted");
        var protoEnum = model.PacketEnum;
        if (protoEnum != null)
        {
            foreach (var value in protoEnum.Values.Where(item => item.Number != 0))
            {
                var name = PacketValueName(value.Name);
                text.AppendLine($"\tconst {GdConstName(name)} := \"{name}\"");
            }
        }
        return text.ToString();
    }

    private static string RenderGdEvent(BridgeModel model)
    {
        var schema = model.Schema;
        var text = new StringBuilder();
        text.AppendLine("class Event:");
        text.AppendLine("\textends RefCounted");
        var eventRoot = model.EventRoot;
        if (eventRoot == null)
        {
            return text.ToString();
        }

        foreach (var variant in eventRoot.Fields.Where(item => item.IsOneof))
        {
            if (!schema.Messages.TryGetValue(variant.Type, out var message))
            {
                continue;
            }
            text.AppendLine();
            text.Append(Indent(RenderGdWrapper(
                GdClassNameForEvent(variant.Type),
                message.Fields,
                eventMode: true,
                schema,
                groupName: "Event",
                classNameForType: GdClassNameForEvent), "\t"));
            text.AppendLine();
        }

        text.AppendLine();
        text.AppendLine("\tclass Bus:");
        text.AppendLine("\t\textends RefCounted");
        text.AppendLine();
        text.AppendLine("\t\tvar _callbacks: Dictionary = {}");
        text.AppendLine();
        text.AppendLine("\t\tfunc clear() -> void:");
        text.AppendLine("\t\t\t_callbacks.clear()");
        foreach (var variant in eventRoot.Fields.Where(item => item.IsOneof))
        {
            var eventKey = ClassNameForEvent(variant.Type);
            text.AppendLine();
            text.AppendLine($"\t\tfunc on_{variant.Name}(cb: Callable) -> void:");
            text.AppendLine($"\t\t\tvar callbacks: Array = _callbacks.get(\"{eventKey}\", [])");
            text.AppendLine("\t\t\tcallbacks.append(cb)");
            text.AppendLine($"\t\t\t_callbacks[\"{eventKey}\"] = callbacks");
        }
        text.AppendLine();
        text.AppendLine("\t\tfunc dispatch(events: Array) -> void:");
        text.AppendLine("\t\t\tfor ev in events:");
        text.AppendLine("\t\t\t\tdispatch_one(ev)");
        text.AppendLine();
        text.AppendLine("\t\tfunc dispatch_one(raw: Dictionary) -> void:");
        text.AppendLine("\t\t\tvar ev_type: String = str(raw.get(\"type\", \"\"))");
        text.AppendLine("\t\t\tvar callbacks: Array = _callbacks.get(ev_type, [])");
        text.AppendLine("\t\t\tif callbacks.is_empty():");
        text.AppendLine("\t\t\t\treturn");
        text.AppendLine("\t\t\tmatch ev_type:");
        foreach (var variant in eventRoot.Fields.Where(item => item.IsOneof))
        {
            var eventKey = ClassNameForEvent(variant.Type);
            var wrapperName = GdClassNameForEvent(variant.Type);
            text.AppendLine($"\t\t\t\t\"{eventKey}\":");
            text.AppendLine($"\t\t\t\t\tvar ev = {wrapperName}.wrap(raw)");
            text.AppendLine("\t\t\t\t\tif ev == null:");
            text.AppendLine("\t\t\t\t\t\treturn");
            text.AppendLine("\t\t\t\t\tfor cb in callbacks:");
            text.AppendLine("\t\t\t\t\t\tif cb.is_valid():");
            text.AppendLine("\t\t\t\t\t\t\tcb.call(ev)");
        }
        text.AppendLine("\t\t\t\t_:");
        text.AppendLine("\t\t\t\t\tpass");
        return text.ToString();
    }

    private static string RenderGdView(BridgeModel model)
    {
        var schema = model.Schema;
        var text = new StringBuilder();
        text.AppendLine("class View:");
        text.AppendLine("\textends RefCounted");
        foreach (var message in model.ViewMessages.OrderBy(item => item.Name, StringComparer.Ordinal))
        {
            text.AppendLine();
            text.Append(Indent(RenderGdWrapper(
                GdClassNameForView(message.Name),
                message.Fields,
                eventMode: false,
                schema,
                groupName: "View",
                classNameForType: GdClassNameForView), "\t"));
            text.AppendLine();
        }
        return text.ToString();
    }

    private static string RenderGdWrapper(
        string className,
        IReadOnlyList<ProtoField> fields,
        bool eventMode,
        ProtoSchema? schema,
        string groupName,
        Func<string, string> classNameForType
    )
    {
        var block = new StringBuilder();
        block.AppendLine($"class {className}:");
        block.AppendLine("\textends RefCounted");
        block.AppendLine();
        block.AppendLine("\tvar _raw: Dictionary = {}");
        block.AppendLine();
        block.AppendLine($"\tstatic func wrap(raw: Dictionary) -> {className}:");
        foreach (var field in fields.Where(field => BridgeNumeric.IsNumeric(field.Type, schema)))
        {
            var fallback = field.IsRepeated ? "[]" : field.Type == "uint64" ? "\"0\"" : "0";
            block.AppendLine($"\t\tif not Bridge.Numeric.valid(raw.get(\"{field.Name}\", {fallback}), \"{field.Type}\", \"{field.Name}\", {field.IsRepeated.ToString().ToLowerInvariant()}):");
            block.AppendLine("\t\t\treturn null");
        }
        block.AppendLine($"\t\tvar obj: {className} = {className}.new()");
        block.AppendLine("\t\tobj._raw = raw");
        block.AppendLine("\t\treturn obj");
        block.AppendLine();
        block.AppendLine("\tfunc raw() -> Dictionary:");
        block.AppendLine("\t\treturn _raw");

        foreach (var field in fields)
        {
            block.AppendLine();
            block.AppendLine($"\tfunc {field.Name}() -> {GdReturnType(schema, field, eventMode)}:");
            block.AppendLine($"\t\treturn {GdGetter(schema, field, eventMode)}");

            if (field.IsRepeated && schema != null && !IsIntLike(field.Type) && schema.Messages.ContainsKey(field.Type))
            {
                var nestedClass = classNameForType(field.Type);
                block.AppendLine();
                block.AppendLine($"\tfunc {field.Name}_wrapped() -> Array:");
                block.AppendLine("\t\tvar out: Array = []");
                block.AppendLine($"\t\tfor item in {field.Name}():");
                block.AppendLine($"\t\t\tout.append({nestedClass}.wrap(item))");
                block.AppendLine("\t\treturn out");
            }
        }

        return block.ToString().TrimEnd();
    }

    private static string Indent(string text, string prefix)
    {
        return string.Join("\n", text.Split('\n').Select(line => line.Length == 0 ? line : prefix + line));
    }
}
