using System.Text;
using static ConfigSchema;

static class ConfigGd
{
    internal static void Stage(
        GenerationBatch batch,
        string root,
        FwConfig config,
        ConfigModel model
    )
    {
        var schema = model.Schema;

        var text = new StringBuilder();
        text.Append(GdRuntimePrelude(model.SchemaHash));
        text.Append(ConfigNumericGd.RuntimePrelude());
        text.AppendLine();
        RenderGdDefaults(text, model.Messages, schema);
        RenderGdParsers(text, model.Messages, schema, false);
        RenderGdParsers(text, model.Messages, schema, true);
        RenderGdLoaders(text, model.Roots, schema);

        var output = config.ConfigGdPath(root);
        batch.StageText(output, text.ToString());
    }

    private static string GdRuntimePrelude(string schemaHash)
    {
        return """
# This file is generated by fwgen. Do not edit manually.
extends RefCounted
class_name _config

const PACK_MAGIC: Array[int] = [87, 67, 70, 71]
const PACK_VERSION: int = 1
const PACK_HEADER_SIZE: int = 76
const PACK_SCHEMA_HASH: String = "__SCHEMA_HASH__"
const FIXED32_SCALE: float = 256.0
static var _error_count: int = 0

static func _fail(message: String) -> void:
	_error_count += 1
	push_error(message)
	assert(false, message)

class _NumericToken:
	var text: String
	func _init(raw: String) -> void:
		text = raw

static func _collect_json_keys(value: Variant, keys: Dictionary) -> void:
	if value is Dictionary:
		for key in value:
			keys[key] = true
			_collect_json_keys(value[key], keys)
	elif value is Array:
		for item in value:
			_collect_json_keys(item, keys)

static func _restore_json_numbers(value: Variant, marker: String) -> Variant:
	if value is Dictionary:
		if value.size() == 1 and value.has(marker):
			return _NumericToken.new(value[marker])
		for key in value:
			value[key] = _restore_json_numbers(value[key], marker)
	elif value is Array:
		for index in range(value.size()):
			value[index] = _restore_json_numbers(value[index], marker)
	return value

static func _parse_json_exact(text: String, ctx: String) -> Variant:
	# Godot still validates JSON structure. Only valid numeric tokens are replaced;
	# strings (including escaped quotes/digits) are never rewritten.
	var json: JSON = JSON.new()
	if json.parse(text) != OK:
		_fail("%s must be valid JSON: %s" % [ctx, json.get_error_message()])
		return null
	var keys: Dictionary = {}
	_collect_json_keys(json.data, keys)
	var marker: String = "__fw_numeric_token"
	while keys.has(marker):
		marker += "_"
	var tokens: RegEx = RegEx.new()
	if tokens.compile('"(?:[^"\\\\]|\\\\.)*"|-?(?:0|[1-9][0-9]*)(?:\\.[0-9]+)?(?:[eE][+-]?[0-9]+)?') != OK:
		_fail("config numeric token pattern is invalid")
		return null
	var pieces: PackedStringArray = []
	var position: int = 0
	for token in tokens.search_all(text):
		var raw: String = token.get_string()
		if raw.begins_with('"'):
			continue
		pieces.append(text.substr(position, token.get_start() - position))
		pieces.append("{%s:%s}" % [JSON.stringify(marker), JSON.stringify(raw)])
		position = token.get_end()
	pieces.append(text.substr(position))
	if json.parse("".join(pieces)) != OK:
		_fail("%s contains an invalid JSON numeric token" % ctx)
		return null
	return _restore_json_numbers(json.data, marker)

static func _normalize_csv_header(header: String, index: int) -> String:
	if index == 0 and not header.is_empty() and header.unicode_at(0) == 0xfeff:
		return header.substr(1)
	return header

static func _read_csv_rows(path: String) -> Array:
	var file: FileAccess = FileAccess.open(path, FileAccess.READ)
	if file == null:
		_fail("failed to open %s" % path)
		return []
	var headers: PackedStringArray = file.get_csv_line()
	var rows: Array = []
	while not file.eof_reached():
		var values: PackedStringArray = file.get_csv_line()
		if values.is_empty():
			continue
		var row: Dictionary = {}
		for index in range(min(headers.size(), values.size())):
			row[_normalize_csv_header(str(headers[index]), index)] = str(values[index])
		rows.append(row)
	return rows

static func _read_json_array(path: String, ctx: String) -> Array:
	var file: FileAccess = FileAccess.open(path, FileAccess.READ)
	if file == null:
		_fail("failed to open %s" % path)
		return []
	var parsed: Variant = _parse_json_exact(file.get_as_text(), ctx)
	if not (parsed is Array):
		_fail("%s must be a json array" % ctx)
		return []
	return parsed

static func _read_u32_le(bytes: PackedByteArray, offset: int) -> int:
	return int(bytes[offset]) \
		| (int(bytes[offset + 1]) << 8) \
		| (int(bytes[offset + 2]) << 16) \
		| (int(bytes[offset + 3]) << 24)

static func _sha256_hex(bytes: PackedByteArray) -> String:
	var hash: HashingContext = HashingContext.new()
	if hash.start(HashingContext.HASH_SHA256) != OK:
		_fail("failed to start config hash")
		return ""
	if hash.update(bytes) != OK:
		_fail("failed to update config hash")
		return ""
	return hash.finish().hex_encode()

static func _read_bin_entries(path: String, ctx: String) -> Array:
	var file: FileAccess = FileAccess.open(path, FileAccess.READ)
	if file == null:
		_fail("failed to open %s" % path)
		return []
	var bytes: PackedByteArray = file.get_buffer(file.get_length())
	if bytes.size() < PACK_HEADER_SIZE:
		_fail("%s binary is too short" % ctx)
		return []
	for index in range(PACK_MAGIC.size()):
		if bytes[index] != PACK_MAGIC[index]:
			_fail("%s binary magic mismatch" % ctx)
			return []
	if _read_u32_le(bytes, 4) != PACK_VERSION:
		_fail("%s binary version mismatch" % ctx)
		return []
	if bytes.slice(8, 40).hex_encode() != PACK_SCHEMA_HASH:
		_fail("%s schema hash mismatch" % ctx)
		return []
	var payload_size: int = _read_u32_le(bytes, 40)
	if payload_size < 0 or PACK_HEADER_SIZE + payload_size != bytes.size():
		_fail("%s payload size mismatch" % ctx)
		return []
	var payload: PackedByteArray = bytes.slice(PACK_HEADER_SIZE, PACK_HEADER_SIZE + payload_size)
	if _sha256_hex(payload) != bytes.slice(44, 76).hex_encode():
		_fail("%s payload hash mismatch" % ctx)
		return []
	var parsed: Variant = _parse_json_exact(payload.get_string_from_utf8(), ctx)
	if not (parsed is Array):
		_fail("%s binary payload must be an array" % ctx)
		return []
	return parsed

static func _cell(row: Dictionary, field: String, ctx: String) -> String:
	if not row.has(field):
		_fail("%s missing column %s" % [ctx, field])
		return ""
	return str(row[field])

static func _has_csv_value(row: Dictionary, field: String) -> bool:
	return row.has(field) and not str(row[field]).strip_edges().is_empty()

static func _as_dictionary(value: Variant, ctx: String) -> Dictionary:
	if not (value is Dictionary):
		_fail("%s must be a dictionary" % ctx)
		return {}
	return value

static func _object_field(obj: Dictionary, field: String, ctx: String) -> Variant:
	if not obj.has(field):
		_fail("%s missing field %s" % [ctx, field])
		return null
	return obj[field]

static func _integer_text(value: Variant, ctx: String, minimum: String, maximum: String) -> String:
	var text: String = ""
	var json_number: bool = value is _NumericToken
	if json_number:
		text = value.text
	elif typeof(value) == TYPE_STRING:
		if str(value).length() > 4096:
			_fail("%s numeric text exceeds 4096 characters" % ctx)
			return "0"
		text = str(value).strip_edges()
	elif typeof(value) == TYPE_INT or typeof(value) == TYPE_FLOAT:
		var number: float = float(value)
		if not is_finite(number) or floor(number) != number or abs(number) > float(9007199254740991):
			_fail("%s must be a safe integer number; use decimal strings for 64-bit values" % ctx)
			return "0"
		text = str(int(value))
	else:
		_fail("%s must be integer text or a number" % ctx)
		return "0"
	if text.length() > 4096:
		_fail("%s numeric text exceeds 4096 characters" % ctx)
		return "0"
	var negative: bool = text.begins_with("-")
	if negative or text.begins_with("+"):
		text = text.substr(1)
	if text.is_empty():
		_fail("%s must contain integer digits" % ctx)
		return "0"
	for index in range(text.length()):
		if text.unicode_at(index) < 48 or text.unicode_at(index) > 57:
			_fail("%s must contain only integer digits" % ctx)
			return "0"
	while text.length() > 1 and text.begins_with("0"):
		text = text.substr(1)
	negative = negative and text != "0"
	if json_number and (text.length() > 16 or (text.length() == 16 and text > "9007199254740991")):
		_fail("%s must be a safe integer number; use decimal strings for 64-bit values" % ctx)
		return "0"
	var bound: String = minimum.substr(1) if negative and minimum.begins_with("-") else maximum
	if (negative and not minimum.begins_with("-")) or text.length() > bound.length() or (text.length() == bound.length() and text > bound):
		_fail("%s integer is outside [%s, %s]" % [ctx, minimum, maximum])
		return "0"
	return ("-" if negative else "") + text

static func _parse_text_int(value: Variant, ctx: String) -> int:
	return int(_integer_text(value, ctx, "-2147483648", "2147483647"))

static func _parse_text_uint(value: Variant, ctx: String) -> int:
	return int(_integer_text(value, ctx, "0", "4294967295"))

static func _parse_text_long(value: Variant, ctx: String) -> int:
	return int(_integer_text(value, ctx, "-9223372036854775808", "9223372036854775807"))

static func _parse_text_ulong(value: Variant, ctx: String) -> String:
	return _integer_text(value, ctx, "0", "18446744073709551615")

static func _parse_text_bool(value: Variant, ctx: String) -> bool:
	match typeof(value):
		TYPE_BOOL:
			return bool(value)
		TYPE_STRING:
			var text: String = str(value).strip_edges().to_lower()
			if text in ["1", "true", "yes"]:
				return true
			if text in ["0", "false", "no"]:
				return false
		_:
			pass
	_fail("%s must be bool-compatible value" % ctx)
	return false

static func _parse_text_fixed(value: Variant, ctx: String) -> float:
	var scaled: float = round(_parse_text_double(value, ctx) * FIXED32_SCALE)
	if not is_finite(scaled) or scaled < -2147483648.0 or scaled > 2147483647.0:
		_fail("%s is outside Q24.8 range" % ctx)
		return 0.0
	return float(int(scaled)) / FIXED32_SCALE

static func _parse_text_float(value: Variant, ctx: String) -> float:
	if value is _NumericToken:
		return _decimal_to_single(value.text, ctx)
	if typeof(value) == TYPE_STRING:
		return _decimal_to_single(str(value), ctx)
	var number: float = _parse_text_double(value, ctx)
	var single: float = PackedFloat32Array([number])[0]
	if not is_finite(single):
		_fail("%s is outside finite float32 range" % ctx)
		return 0.0
	return single

static func _parse_text_double(value: Variant, ctx: String) -> float:
	if value is _NumericToken:
		return _decimal_to_double(value.text, ctx)
	if typeof(value) == TYPE_STRING:
		return _decimal_to_double(str(value), ctx)
	if typeof(value) != TYPE_INT and typeof(value) != TYPE_FLOAT:
		_fail("%s must be float-compatible value" % ctx)
		return 0.0
	var number: float = float(value)
	if not is_finite(number):
		_fail("%s must be a finite double" % ctx)
		return 0.0
	return number

static func _parse_text_string(value: Variant, _ctx: String) -> String:
	if value is _NumericToken:
		return value.text
	return str(value)

static func _parse_text_array(value: Variant, ctx: String, item_parser: Callable) -> Array:
	if not (value is Array):
		_fail("%s must be an array" % ctx)
		return []
	var items: Array = value
	var out: Array = []
	for index in range(items.size()):
		out.append(item_parser.call(items[index], "%s[%d]" % [ctx, index]))
	return out

static func _parse_bin_int(value: Variant, ctx: String) -> int:
	return _parse_text_int(value, ctx)

static func _parse_bin_uint(value: Variant, ctx: String) -> int:
	return _parse_text_uint(value, ctx)

static func _parse_bin_long(value: Variant, ctx: String) -> int:
	return _parse_text_long(value, ctx)

static func _parse_bin_ulong(value: Variant, ctx: String) -> String:
	return _parse_text_ulong(value, ctx)

static func _parse_bin_bool(value: Variant, ctx: String) -> bool:
	if typeof(value) == TYPE_BOOL:
		return bool(value)
	_fail("%s must be bool" % ctx)
	return false

static func _parse_bin_fixed(value: Variant, ctx: String) -> float:
	return float(_parse_bin_int(value, ctx)) / FIXED32_SCALE

static func _parse_bin_float(value: Variant, ctx: String) -> float:
	return _parse_text_float(value, ctx)

static func _parse_bin_double(value: Variant, ctx: String) -> float:
	return _parse_text_double(value, ctx)

static func _parse_bin_string(value: Variant, ctx: String) -> String:
	if typeof(value) == TYPE_STRING:
		return str(value)
	_fail("%s must be string" % ctx)
	return ""

static func _parse_bin_array(value: Variant, ctx: String, item_parser: Callable) -> Array:
	if not (value is Array):
		_fail("%s must be an array" % ctx)
		return []
	var items: Array = value
	var out: Array = []
	for index in range(items.size()):
		out.append(item_parser.call(items[index], "%s[%d]" % [ctx, index]))
	return out

static func _clone_value(value: Variant) -> Variant:
	if value is Dictionary:
		var out: Dictionary = {}
		for key in value.keys():
			out[key] = _clone_value(value[key])
		out.make_read_only()
		return out
	if value is Array:
		var out: Array = []
		for item in value:
			out.append(_clone_value(item))
		out.make_read_only()
		return out
	return value

static func _clone_by_key(entries: Array, key: String) -> Dictionary:
	for item in entries:
		var entry: Dictionary = _as_dictionary(item, "entry")
		if str(entry.get("key", "")) == key:
			return entry.get("value", {})
	return _clone_value({})

static func _clone_required_by_key(entries: Array, key: String, ctx: String) -> Dictionary:
	var value: Dictionary = _clone_by_key(entries, key)
	if value.is_empty():
		_fail("%s references missing key %s" % [ctx, key])
	return value

static func _clone_by_index(entries: Array, index: int) -> Dictionary:
	if index < 0 or index >= entries.size():
		return _clone_value({})
	var entry: Dictionary = _as_dictionary(entries[index], "entry")
	return entry.get("value", {})

static func _clone_all(entries: Array) -> Array:
	return entries

""".Replace("__SCHEMA_HASH__", schemaHash, StringComparison.Ordinal);
    }

    private static void RenderGdDefaults(StringBuilder text, IEnumerable<ProtoMessage> messages, ProtoSchema schema)
    {
        foreach (var message in messages)
        {
            var name = TextUtil.Snake(message.Name);
            text.AppendLine($"static func _default_{name}() -> Dictionary:");
            text.AppendLine("\treturn {");
            foreach (var field in message.Fields)
            {
                text.AppendLine($"\t\t\"{field.Name}\": {GdDefaultExpr(field, schema)},");
            }
            text.AppendLine("\t}");
            text.AppendLine();
        }
    }

    private static void RenderGdParsers(
        StringBuilder text,
        IEnumerable<ProtoMessage> messages,
        ProtoSchema schema,
        bool binary
    )
    {
        var mode = binary ? "bin" : "text";
        foreach (var message in messages)
        {
            var name = TextUtil.Snake(message.Name);
            text.AppendLine($"static func _parse_{mode}_{name}(value: Variant, ctx: String) -> Dictionary:");
            text.AppendLine("\tvar obj: Dictionary = _as_dictionary(value, ctx)");
            text.AppendLine("\treturn {");
            foreach (var field in message.Fields)
            {
                var ctx = $"\"%s.{field.Name}\" % ctx";
                var expr = GdFieldParseExpr(field, schema, binary, $"_object_field(obj, \"{field.Name}\", ctx)", ctx);
                var fallback = GdMissingFieldExpr(field, schema);
                text.AppendLine($"\t\t\"{field.Name}\": {expr} if obj.has(\"{field.Name}\") else {fallback},");
            }
            text.AppendLine("\t}");
            text.AppendLine();
        }
    }

    private static void RenderGdLoaders(StringBuilder text, IEnumerable<ConfigRoot> roots, ProtoSchema schema)
    {
        foreach (var root in roots)
        {
            text.AppendLine($"static var _{root.Name}_loaded: bool = false");
            text.AppendLine($"static var _{root.Name}_entries: Array = []");
            text.AppendLine();

            if (root.IsJson)
            {
                RenderGdJsonLoader(text, root);
            }
            else
            {
                RenderGdCsvLoader(text, root, schema);
            }
            RenderGdBinLoader(text, root);
            RenderGdEntryAccess(text, root);
        }
    }

    private static void RenderGdCsvLoader(StringBuilder text, ConfigRoot root, ProtoSchema schema)
    {
        text.AppendLine($"static func _load_{root.Name}_text() -> Array:");
        text.AppendLine($"\tvar rows: Array = _read_csv_rows(\"{root.SourcePath}\")");
        text.AppendLine("\tvar entries: Array = []");
        text.AppendLine("\tfor index in range(rows.size()):");
        text.AppendLine("\t\tvar row: Dictionary = rows[index]");
        text.AppendLine($"\t\tvar ctx: String = \"{root.Name}[%d]\" % index");
        text.AppendLine("\t\tvar value: Dictionary = {");
        foreach (var field in root.Message.Fields)
        {
            var ctx = $"\"%s.{field.Name}\" % ctx";
            var expr = GdCsvFieldExpr(field, schema, $"_cell(row, \"{field.Name}\", ctx)", ctx);
            var fallback = GdMissingFieldExpr(field, schema);
            text.AppendLine($"\t\t\t\"{field.Name}\": {expr} if _has_csv_value(row, \"{field.Name}\") else {fallback},");
        }
        text.AppendLine("\t\t}");
        text.AppendLine("\t\tentries.append({\"key\": _cell(row, \"key\", ctx), \"value\": value})");
        text.AppendLine("\treturn entries");
        text.AppendLine();
    }

    private static void RenderGdJsonLoader(StringBuilder text, ConfigRoot root)
    {
        var parseName = TextUtil.Snake(root.Message.Name);
        text.AppendLine($"static func _load_{root.Name}_text() -> Array:");
        text.AppendLine($"\tvar items: Array = _read_json_array(\"{root.SourcePath}\", \"{root.Name}\")");
        text.AppendLine("\tvar entries: Array = []");
        text.AppendLine("\tfor index in range(items.size()):");
        text.AppendLine($"\t\tvar item: Dictionary = _as_dictionary(items[index], \"%s[%d]\" % [\"{root.Name}\", index])");
        text.AppendLine($"\t\tvar ctx: String = \"{root.Name}[%d]\" % index");
        text.AppendLine($"\t\tentries.append({{\"key\": _parse_bin_string(_object_field(item, \"key\", ctx), \"%s.key\" % ctx), \"value\": _parse_text_{parseName}(item, ctx)}})");
        text.AppendLine("\treturn entries");
        text.AppendLine();
    }

    private static void RenderGdBinLoader(StringBuilder text, ConfigRoot root)
    {
        var parseName = TextUtil.Snake(root.Message.Name);
        text.AppendLine($"static func _load_{root.Name}_bin() -> Array:");
        text.AppendLine($"\tvar raw_entries: Array = _read_bin_entries(\"{root.PackPath}\", \"{root.Name}\")");
        text.AppendLine("\tvar entries: Array = []");
        text.AppendLine("\tfor index in range(raw_entries.size()):");
        text.AppendLine($"\t\tvar item: Dictionary = _as_dictionary(raw_entries[index], \"%s[%d]\" % [\"{root.Name}\", index])");
        text.AppendLine($"\t\tvar ctx: String = \"{root.Name}[%d]\" % index");
        text.AppendLine($"\t\tentries.append({{\"key\": _parse_bin_string(_object_field(item, \"key\", ctx), \"%s.key\" % ctx), \"value\": _parse_bin_{parseName}(_object_field(item, \"value\", ctx), \"%s.value\" % ctx)}})");
        text.AppendLine("\treturn entries");
        text.AppendLine();
    }

    private static void RenderGdEntryAccess(StringBuilder text, ConfigRoot root)
    {
        text.AppendLine($"static func _load_{root.Name}_entries() -> Array:");
        text.AppendLine($"\tif _{root.Name}_loaded:");
        text.AppendLine($"\t\treturn _{root.Name}_entries");
        text.AppendLine("\tvar errors_before: int = _error_count");
        text.AppendLine("\tvar loaded: Array");
        text.AppendLine("\tif OS.has_feature(\"editor\"):");
        text.AppendLine($"\t\tloaded = _load_{root.Name}_text()");
        text.AppendLine("\telse:");
        text.AppendLine($"\t\tloaded = _load_{root.Name}_bin()");
        text.AppendLine("\tif _error_count != errors_before:");
        text.AppendLine("\t\treturn _clone_value([])");
        text.AppendLine($"\t_{root.Name}_entries = _clone_value(loaded)");
        text.AppendLine($"\t_{root.Name}_loaded = true");
        text.AppendLine($"\treturn _{root.Name}_entries");
        text.AppendLine();
        text.AppendLine($"static func {root.Name}_by_key(key: String) -> Dictionary:");
        text.AppendLine($"\treturn _clone_by_key(_load_{root.Name}_entries(), key)");
        text.AppendLine();
        text.AppendLine($"static func {root.Name}_by_index(index: int) -> Dictionary:");
        text.AppendLine($"\treturn _clone_by_index(_load_{root.Name}_entries(), index)");
        text.AppendLine();
        text.AppendLine($"static func {root.Name}_all() -> Array:");
        text.AppendLine($"\treturn _clone_all(_load_{root.Name}_entries())");
        text.AppendLine();
        text.AppendLine($"static func {root.Name}_default_config() -> Dictionary:");
        text.AppendLine($"\tvar value: Dictionary = {root.Name}_by_key(\"default\")");
        text.AppendLine("\tif value.is_empty():");
        text.AppendLine($"\t\t_fail(\"generated config source must contain default for {root.Name}\")");
        text.AppendLine("\t\treturn _clone_value({})");
        text.AppendLine("\treturn value");
        text.AppendLine();
    }

    private static string GdCsvFieldExpr(ProtoField field, ProtoSchema schema, string valueExpr, string ctxExpr)
    {
        if (field.IsRepeated)
        {
            return $"_parse_text_array(_parse_json_exact({valueExpr}, {ctxExpr}), {ctxExpr}, {GdParserName(field.Type, false)})";
        }
        if (IsMessageType(field.Type, schema) && field.Type != "Fixed32")
        {
            if (IsConfigMessage(field.Type))
            {
                return $"_clone_required_by_key(_load_{ConfigRootName(field.Type)}_entries(), {valueExpr}, {ctxExpr})";
            }
            return $"_parse_text_{TextUtil.Snake(field.Type)}(_parse_json_exact({valueExpr}, {ctxExpr}), {ctxExpr})";
        }
        return $"{GdScalarParser(field.Type, false)}({valueExpr}, {ctxExpr})";
    }

    private static string GdFieldParseExpr(
        ProtoField field,
        ProtoSchema schema,
        bool binary,
        string valueExpr,
        string ctxExpr
    )
    {
        var mode = binary ? "bin" : "text";
        if (field.IsRepeated)
        {
            return $"_parse_{mode}_array({valueExpr}, {ctxExpr}, {GdParserName(field.Type, binary)})";
        }
        if (IsMessageType(field.Type, schema) && field.Type != "Fixed32")
        {
            var parser = $"_parse_{mode}_{TextUtil.Snake(field.Type)}({valueExpr}, {ctxExpr})";
            if (!IsConfigMessage(field.Type))
            {
                return parser;
            }
            var rootName = ConfigRootName(field.Type);
            return $"(_clone_required_by_key(_load_{rootName}_entries(), str({valueExpr}), {ctxExpr}) if typeof({valueExpr}) == TYPE_STRING else {parser})";
        }
        return $"{GdScalarParser(field.Type, binary)}({valueExpr}, {ctxExpr})";
    }

    private static string GdParserName(string type, bool binary)
    {
        if (type == "Fixed32")
        {
            return binary ? "_parse_bin_fixed" : "_parse_text_fixed";
        }
        return type switch
        {
            "string" => binary ? "_parse_bin_string" : "_parse_text_string",
            "bool" => binary ? "_parse_bin_bool" : "_parse_text_bool",
            "float" => binary ? "_parse_bin_float" : "_parse_text_float",
            "double" => binary ? "_parse_bin_double" : "_parse_text_double",
            "uint32" => binary ? "_parse_bin_uint" : "_parse_text_uint",
            "uint64" => binary ? "_parse_bin_ulong" : "_parse_text_ulong",
            "int64" or "sint64" => binary ? "_parse_bin_long" : "_parse_text_long",
            "int32" or "sint32" => binary ? "_parse_bin_int" : "_parse_text_int",
            _ => binary ? $"_parse_bin_{TextUtil.Snake(type)}" : $"_parse_text_{TextUtil.Snake(type)}",
        };
    }

    private static string GdScalarParser(string type, bool binary)
    {
        return GdParserName(type, binary);
    }

    private static string GdMissingFieldExpr(ProtoField field, ProtoSchema schema)
    {
        if (field.IsRepeated)
        {
            return "[]";
        }
        if (IsMessageType(field.Type, schema) && field.Type != "Fixed32")
        {
            return IsConfigMessage(field.Type)
                ? $"_clone_required_by_key(_load_{ConfigRootName(field.Type)}_entries(), \"default\", \"%s.{field.Name}\" % ctx)"
                : $"_default_{TextUtil.Snake(field.Type)}()";
        }
        return GdDefaultExpr(field, schema);
    }

    private static string GdDefaultExpr(ProtoField field, ProtoSchema schema)
    {
        if (field.IsRepeated)
        {
            return "[]";
        }
        if (field.Type == "Fixed32" || field.Type is "float" or "double")
        {
            return "0.0";
        }
        if (field.Type == "bool")
        {
            return "false";
        }
        if (field.Type == "string")
        {
            return "\"\"";
        }
        if (field.Type == "uint64")
        {
            return "\"0\"";
        }
        if (IsMessageType(field.Type, schema))
        {
            return "{}";
        }
        return "0";
    }
}
