using System.Text;
using static ConfigSchema;

static class ConfigGd
{
    internal static void Stage(
        GenerationBatch batch,
        string root,
        FwConfig config,
        ConfigModel model
    )
    {
        var schema = model.Schema;

        var text = new StringBuilder();
        text.Append(GdRuntimePrelude(model.SchemaHash));
        RenderGdDefaults(text, model.Messages, schema);
        RenderGdParsers(text, model.Messages, schema, false);
        RenderGdParsers(text, model.Messages, schema, true);
        RenderGdLoaders(text, model.Roots, schema);

        var output = config.ConfigGdPath(root);
        batch.StageText(output, text.ToString());
    }

    private static string GdRuntimePrelude(string schemaHash)
    {
        return """
# This file is generated by fwgen. Do not edit manually.
extends RefCounted
class_name _config

const PACK_MAGIC: Array[int] = [87, 67, 70, 71]
const PACK_VERSION: int = 1
const PACK_HEADER_SIZE: int = 76
const PACK_SCHEMA_HASH: String = "__SCHEMA_HASH__"
const FIXED32_SCALE: float = 256.0

static func _fail(message: String) -> void:
	push_error(message)
	assert(false, message)

static func _normalize_csv_header(header: String, index: int) -> String:
	if index == 0 and not header.is_empty() and header.unicode_at(0) == 0xfeff:
		return header.substr(1)
	return header

static func _read_csv_rows(path: String) -> Array:
	var file: FileAccess = FileAccess.open(path, FileAccess.READ)
	if file == null:
		_fail("failed to open %s" % path)
		return []
	var headers: PackedStringArray = file.get_csv_line()
	var rows: Array = []
	while not file.eof_reached():
		var values: PackedStringArray = file.get_csv_line()
		if values.is_empty():
			continue
		var row: Dictionary = {}
		for index in range(min(headers.size(), values.size())):
			row[_normalize_csv_header(str(headers[index]), index)] = str(values[index])
		rows.append(row)
	return rows

static func _read_json_array(path: String, ctx: String) -> Array:
	var file: FileAccess = FileAccess.open(path, FileAccess.READ)
	if file == null:
		_fail("failed to open %s" % path)
		return []
	var parsed: Variant = JSON.parse_string(file.get_as_text())
	if not (parsed is Array):
		_fail("%s must be a json array" % ctx)
		return []
	return parsed

static func _read_u32_le(bytes: PackedByteArray, offset: int) -> int:
	return int(bytes[offset]) \
		| (int(bytes[offset + 1]) << 8) \
		| (int(bytes[offset + 2]) << 16) \
		| (int(bytes[offset + 3]) << 24)

static func _sha256_hex(bytes: PackedByteArray) -> String:
	var hash: HashingContext = HashingContext.new()
	if hash.start(HashingContext.HASH_SHA256) != OK:
		_fail("failed to start config hash")
		return ""
	if hash.update(bytes) != OK:
		_fail("failed to update config hash")
		return ""
	return hash.finish().hex_encode()

static func _read_bin_entries(path: String, ctx: String) -> Array:
	var file: FileAccess = FileAccess.open(path, FileAccess.READ)
	if file == null:
		_fail("failed to open %s" % path)
		return []
	var bytes: PackedByteArray = file.get_buffer(file.get_length())
	if bytes.size() < PACK_HEADER_SIZE:
		_fail("%s binary is too short" % ctx)
		return []
	for index in range(PACK_MAGIC.size()):
		if bytes[index] != PACK_MAGIC[index]:
			_fail("%s binary magic mismatch" % ctx)
			return []
	if _read_u32_le(bytes, 4) != PACK_VERSION:
		_fail("%s binary version mismatch" % ctx)
		return []
	if bytes.slice(8, 40).hex_encode() != PACK_SCHEMA_HASH:
		_fail("%s schema hash mismatch" % ctx)
		return []
	var payload_size: int = _read_u32_le(bytes, 40)
	if payload_size < 0 or PACK_HEADER_SIZE + payload_size != bytes.size():
		_fail("%s payload size mismatch" % ctx)
		return []
	var payload: PackedByteArray = bytes.slice(PACK_HEADER_SIZE, PACK_HEADER_SIZE + payload_size)
	if _sha256_hex(payload) != bytes.slice(44, 76).hex_encode():
		_fail("%s payload hash mismatch" % ctx)
		return []
	var parsed: Variant = JSON.parse_string(payload.get_string_from_utf8())
	if not (parsed is Array):
		_fail("%s binary payload must be an array" % ctx)
		return []
	return parsed

static func _cell(row: Dictionary, field: String, ctx: String) -> String:
	if not row.has(field):
		_fail("%s missing column %s" % [ctx, field])
		return ""
	return str(row[field])

static func _has_csv_value(row: Dictionary, field: String) -> bool:
	return row.has(field) and not str(row[field]).strip_edges().is_empty()

static func _as_dictionary(value: Variant, ctx: String) -> Dictionary:
	if not (value is Dictionary):
		_fail("%s must be a dictionary" % ctx)
		return {}
	return value

static func _object_field(obj: Dictionary, field: String, ctx: String) -> Variant:
	if not obj.has(field):
		_fail("%s missing field %s" % [ctx, field])
		return null
	return obj[field]

static func _parse_text_int(value: Variant, ctx: String) -> int:
	match typeof(value):
		TYPE_STRING:
			var text: String = str(value).strip_edges()
			if not text.is_valid_int():
				_fail("%s must be int-compatible text" % ctx)
				return 0
			return int(text)
		TYPE_INT, TYPE_FLOAT:
			return int(value)
		_:
			_fail("%s must be int-compatible value" % ctx)
			return 0

static func _parse_text_bool(value: Variant, ctx: String) -> bool:
	match typeof(value):
		TYPE_BOOL:
			return bool(value)
		TYPE_STRING:
			var text: String = str(value).strip_edges().to_lower()
			if text in ["1", "true", "yes"]:
				return true
			if text in ["0", "false", "no"]:
				return false
		_:
			pass
	_fail("%s must be bool-compatible value" % ctx)
	return false

static func _parse_text_fixed(value: Variant, ctx: String) -> float:
	return _parse_text_float(value, ctx)

static func _parse_text_float(value: Variant, ctx: String) -> float:
	match typeof(value):
		TYPE_STRING:
			var text: String = str(value).strip_edges()
			if not text.is_valid_float() and not text.is_valid_int():
				_fail("%s must be float-compatible text" % ctx)
				return 0.0
			return float(text)
		TYPE_INT, TYPE_FLOAT:
			return float(value)
		_:
			_fail("%s must be float-compatible value" % ctx)
			return 0.0

static func _parse_text_string(value: Variant, _ctx: String) -> String:
	return str(value)

static func _parse_text_array(value: Variant, ctx: String, item_parser: Callable) -> Array:
	if not (value is Array):
		_fail("%s must be an array" % ctx)
		return []
	var items: Array = value
	var out: Array = []
	for index in range(items.size()):
		out.append(item_parser.call(items[index], "%s[%d]" % [ctx, index]))
	return out

static func _parse_bin_int(value: Variant, ctx: String) -> int:
	match typeof(value):
		TYPE_INT, TYPE_FLOAT:
			return int(value)
		TYPE_STRING:
			var text: String = str(value).strip_edges()
			if not text.is_valid_int():
				_fail("%s must be int-compatible text" % ctx)
				return 0
			return int(text)
		_:
			_fail("%s must be int-compatible value" % ctx)
			return 0

static func _parse_bin_bool(value: Variant, ctx: String) -> bool:
	if typeof(value) == TYPE_BOOL:
		return bool(value)
	_fail("%s must be bool" % ctx)
	return false

static func _parse_bin_fixed(value: Variant, ctx: String) -> float:
	return _parse_bin_float(value, ctx) / FIXED32_SCALE

static func _parse_bin_float(value: Variant, ctx: String) -> float:
	match typeof(value):
		TYPE_INT, TYPE_FLOAT:
			return float(value)
		TYPE_STRING:
			var text: String = str(value).strip_edges()
			if not text.is_valid_float() and not text.is_valid_int():
				_fail("%s must be float-compatible text" % ctx)
				return 0.0
			return float(text)
		_:
			_fail("%s must be float-compatible value" % ctx)
			return 0.0

static func _parse_bin_string(value: Variant, ctx: String) -> String:
	if typeof(value) == TYPE_STRING:
		return str(value)
	_fail("%s must be string" % ctx)
	return ""

static func _parse_bin_array(value: Variant, ctx: String, item_parser: Callable) -> Array:
	if not (value is Array):
		_fail("%s must be an array" % ctx)
		return []
	var items: Array = value
	var out: Array = []
	for index in range(items.size()):
		out.append(item_parser.call(items[index], "%s[%d]" % [ctx, index]))
	return out

static func _clone_value(value: Variant) -> Variant:
	if value is Dictionary:
		var out: Dictionary = {}
		for key in value.keys():
			out[key] = _clone_value(value[key])
		return out
	if value is Array:
		var out: Array = []
		for item in value:
			out.append(_clone_value(item))
		return out
	return value

static func _clone_by_key(entries: Array, key: String) -> Dictionary:
	for item in entries:
		var entry: Dictionary = _as_dictionary(item, "entry")
		if str(entry.get("key", "")) == key:
			return _clone_value(entry.get("value", {}))
	return {}

static func _clone_required_by_key(entries: Array, key: String, ctx: String) -> Dictionary:
	var value: Dictionary = _clone_by_key(entries, key)
	if value.is_empty():
		_fail("%s references missing key %s" % [ctx, key])
	return value

static func _clone_by_index(entries: Array, index: int) -> Dictionary:
	if index < 0 or index >= entries.size():
		return {}
	var entry: Dictionary = _as_dictionary(entries[index], "entry")
	return _clone_value(entry.get("value", {}))

static func _clone_all(entries: Array) -> Array:
	var out: Array = []
	for item in entries:
		var entry: Dictionary = _as_dictionary(item, "entry")
		out.append({
			"key": str(entry.get("key", "")),
			"value": _clone_value(entry.get("value", {})),
		})
	return out

""".Replace("__SCHEMA_HASH__", schemaHash, StringComparison.Ordinal);
    }

    private static void RenderGdDefaults(StringBuilder text, IEnumerable<ProtoMessage> messages, ProtoSchema schema)
    {
        foreach (var message in messages)
        {
            var name = TextUtil.Snake(message.Name);
            text.AppendLine($"static func _default_{name}() -> Dictionary:");
            text.AppendLine("\treturn {");
            foreach (var field in message.Fields)
            {
                text.AppendLine($"\t\t\"{field.Name}\": {GdDefaultExpr(field, schema)},");
            }
            text.AppendLine("\t}");
            text.AppendLine();
        }
    }

    private static void RenderGdParsers(
        StringBuilder text,
        IEnumerable<ProtoMessage> messages,
        ProtoSchema schema,
        bool binary
    )
    {
        var mode = binary ? "bin" : "text";
        foreach (var message in messages)
        {
            var name = TextUtil.Snake(message.Name);
            text.AppendLine($"static func _parse_{mode}_{name}(value: Variant, ctx: String) -> Dictionary:");
            text.AppendLine("\tvar obj: Dictionary = _as_dictionary(value, ctx)");
            text.AppendLine("\treturn {");
            foreach (var field in message.Fields)
            {
                var ctx = $"\"%s.{field.Name}\" % ctx";
                var expr = GdFieldParseExpr(field, schema, binary, $"_object_field(obj, \"{field.Name}\", ctx)", ctx);
                var fallback = GdMissingFieldExpr(field, schema);
                text.AppendLine($"\t\t\"{field.Name}\": {expr} if obj.has(\"{field.Name}\") else {fallback},");
            }
            text.AppendLine("\t}");
            text.AppendLine();
        }
    }

    private static void RenderGdLoaders(StringBuilder text, IEnumerable<ConfigRoot> roots, ProtoSchema schema)
    {
        foreach (var root in roots)
        {
            text.AppendLine($"static var _{root.Name}_loaded: bool = false");
            text.AppendLine($"static var _{root.Name}_entries: Array = []");
            text.AppendLine();

            if (root.IsJson)
            {
                RenderGdJsonLoader(text, root);
            }
            else
            {
                RenderGdCsvLoader(text, root, schema);
            }
            RenderGdBinLoader(text, root);
            RenderGdEntryAccess(text, root);
        }
    }

    private static void RenderGdCsvLoader(StringBuilder text, ConfigRoot root, ProtoSchema schema)
    {
        text.AppendLine($"static func _load_{root.Name}_text() -> Array:");
        text.AppendLine($"\tvar rows: Array = _read_csv_rows(\"{root.SourcePath}\")");
        text.AppendLine("\tvar entries: Array = []");
        text.AppendLine("\tfor index in range(rows.size()):");
        text.AppendLine("\t\tvar row: Dictionary = rows[index]");
        text.AppendLine($"\t\tvar ctx: String = \"{root.Name}[%d]\" % index");
        text.AppendLine("\t\tvar value: Dictionary = {");
        foreach (var field in root.Message.Fields)
        {
            var ctx = $"\"%s.{field.Name}\" % ctx";
            var expr = GdCsvFieldExpr(field, schema, $"_cell(row, \"{field.Name}\", ctx)", ctx);
            var fallback = GdMissingFieldExpr(field, schema);
            text.AppendLine($"\t\t\t\"{field.Name}\": {expr} if _has_csv_value(row, \"{field.Name}\") else {fallback},");
        }
        text.AppendLine("\t\t}");
        text.AppendLine("\t\tentries.append({\"key\": _cell(row, \"key\", ctx), \"value\": value})");
        text.AppendLine("\treturn entries");
        text.AppendLine();
    }

    private static void RenderGdJsonLoader(StringBuilder text, ConfigRoot root)
    {
        var parseName = TextUtil.Snake(root.Message.Name);
        text.AppendLine($"static func _load_{root.Name}_text() -> Array:");
        text.AppendLine($"\tvar items: Array = _read_json_array(\"{root.SourcePath}\", \"{root.Name}\")");
        text.AppendLine("\tvar entries: Array = []");
        text.AppendLine("\tfor index in range(items.size()):");
        text.AppendLine($"\t\tvar item: Dictionary = _as_dictionary(items[index], \"%s[%d]\" % [\"{root.Name}\", index])");
        text.AppendLine($"\t\tvar ctx: String = \"{root.Name}[%d]\" % index");
        text.AppendLine($"\t\tentries.append({{\"key\": _parse_text_string(_object_field(item, \"key\", ctx), \"%s.key\" % ctx), \"value\": _parse_text_{parseName}(item, ctx)}})");
        text.AppendLine("\treturn entries");
        text.AppendLine();
    }

    private static void RenderGdBinLoader(StringBuilder text, ConfigRoot root)
    {
        var parseName = TextUtil.Snake(root.Message.Name);
        text.AppendLine($"static func _load_{root.Name}_bin() -> Array:");
        text.AppendLine($"\tvar raw_entries: Array = _read_bin_entries(\"{root.PackPath}\", \"{root.Name}\")");
        text.AppendLine("\tvar entries: Array = []");
        text.AppendLine("\tfor index in range(raw_entries.size()):");
        text.AppendLine($"\t\tvar item: Dictionary = _as_dictionary(raw_entries[index], \"%s[%d]\" % [\"{root.Name}\", index])");
        text.AppendLine($"\t\tvar ctx: String = \"{root.Name}[%d]\" % index");
        text.AppendLine($"\t\tentries.append({{\"key\": _parse_bin_string(_object_field(item, \"key\", ctx), \"%s.key\" % ctx), \"value\": _parse_bin_{parseName}(_object_field(item, \"value\", ctx), \"%s.value\" % ctx)}})");
        text.AppendLine("\treturn entries");
        text.AppendLine();
    }

    private static void RenderGdEntryAccess(StringBuilder text, ConfigRoot root)
    {
        text.AppendLine($"static func _load_{root.Name}_entries() -> Array:");
        text.AppendLine($"\tif _{root.Name}_loaded:");
        text.AppendLine($"\t\treturn _{root.Name}_entries");
        text.AppendLine("\tif OS.has_feature(\"editor\"):");
        text.AppendLine($"\t\t_{root.Name}_entries = _load_{root.Name}_text()");
        text.AppendLine("\telse:");
        text.AppendLine($"\t\t_{root.Name}_entries = _load_{root.Name}_bin()");
        text.AppendLine($"\t_{root.Name}_loaded = true");
        text.AppendLine($"\treturn _{root.Name}_entries");
        text.AppendLine();
        text.AppendLine($"static func {root.Name}_by_key(key: String) -> Dictionary:");
        text.AppendLine($"\treturn _clone_by_key(_load_{root.Name}_entries(), key)");
        text.AppendLine();
        text.AppendLine($"static func {root.Name}_by_index(index: int) -> Dictionary:");
        text.AppendLine($"\treturn _clone_by_index(_load_{root.Name}_entries(), index)");
        text.AppendLine();
        text.AppendLine($"static func {root.Name}_all() -> Array:");
        text.AppendLine($"\treturn _clone_all(_load_{root.Name}_entries())");
        text.AppendLine();
        text.AppendLine($"static func {root.Name}_default_config() -> Dictionary:");
        text.AppendLine($"\tvar value: Dictionary = {root.Name}_by_key(\"default\")");
        text.AppendLine("\tif value.is_empty():");
        text.AppendLine($"\t\t_fail(\"generated config source must contain default for {root.Name}\")");
        text.AppendLine($"\t\treturn _default_{root.Name}_config()");
        text.AppendLine("\treturn value");
        text.AppendLine();
    }

    private static string GdCsvFieldExpr(ProtoField field, ProtoSchema schema, string valueExpr, string ctxExpr)
    {
        if (field.IsRepeated)
        {
            return $"_parse_text_array(JSON.parse_string({valueExpr}), {ctxExpr}, {GdParserName(field.Type, false)})";
        }
        if (IsMessageType(field.Type, schema) && field.Type != "Fixed32")
        {
            if (IsConfigMessage(field.Type))
            {
                return $"_clone_required_by_key(_load_{ConfigRootName(field.Type)}_entries(), {valueExpr}, {ctxExpr})";
            }
            return $"_parse_text_{TextUtil.Snake(field.Type)}(JSON.parse_string({valueExpr}), {ctxExpr})";
        }
        return $"{GdScalarParser(field.Type, false)}({valueExpr}, {ctxExpr})";
    }

    private static string GdFieldParseExpr(
        ProtoField field,
        ProtoSchema schema,
        bool binary,
        string valueExpr,
        string ctxExpr
    )
    {
        var mode = binary ? "bin" : "text";
        if (field.IsRepeated)
        {
            return $"_parse_{mode}_array({valueExpr}, {ctxExpr}, {GdParserName(field.Type, binary)})";
        }
        if (IsMessageType(field.Type, schema) && field.Type != "Fixed32")
        {
            var parser = $"_parse_{mode}_{TextUtil.Snake(field.Type)}({valueExpr}, {ctxExpr})";
            if (!IsConfigMessage(field.Type))
            {
                return parser;
            }
            var rootName = ConfigRootName(field.Type);
            return $"(_clone_required_by_key(_load_{rootName}_entries(), str({valueExpr}), {ctxExpr}) if typeof({valueExpr}) == TYPE_STRING else {parser})";
        }
        return $"{GdScalarParser(field.Type, binary)}({valueExpr}, {ctxExpr})";
    }

    private static string GdParserName(string type, bool binary)
    {
        if (type == "Fixed32")
        {
            return binary ? "_parse_bin_fixed" : "_parse_text_fixed";
        }
        return type switch
        {
            "string" => binary ? "_parse_bin_string" : "_parse_text_string",
            "bool" => binary ? "_parse_bin_bool" : "_parse_text_bool",
            "float" or "double" => binary ? "_parse_bin_float" : "_parse_text_float",
            "uint32" or "uint64" or "int32" or "sint32" or "int64" or "sint64" => binary ? "_parse_bin_int" : "_parse_text_int",
            _ => binary ? $"_parse_bin_{TextUtil.Snake(type)}" : $"_parse_text_{TextUtil.Snake(type)}",
        };
    }

    private static string GdScalarParser(string type, bool binary)
    {
        return GdParserName(type, binary);
    }

    private static string GdMissingFieldExpr(ProtoField field, ProtoSchema schema)
    {
        if (field.IsRepeated)
        {
            return "[]";
        }
        if (IsMessageType(field.Type, schema) && field.Type != "Fixed32")
        {
            return IsConfigMessage(field.Type)
                ? $"_clone_required_by_key(_load_{ConfigRootName(field.Type)}_entries(), \"default\", \"%s.{field.Name}\" % ctx)"
                : $"_default_{TextUtil.Snake(field.Type)}()";
        }
        return GdDefaultExpr(field, schema);
    }

    private static string GdDefaultExpr(ProtoField field, ProtoSchema schema)
    {
        if (field.IsRepeated)
        {
            return "[]";
        }
        if (field.Type == "Fixed32" || field.Type is "float" or "double")
        {
            return "0.0";
        }
        if (field.Type == "bool")
        {
            return "false";
        }
        if (field.Type == "string")
        {
            return "\"\"";
        }
        if (IsMessageType(field.Type, schema))
        {
            return "{}";
        }
        return "0";
    }
}
