using System.Text;
using static ConfigSchema;

static class ConfigCs
{
    internal static void Stage(
        GenerationBatch batch,
        string root,
        FwConfig config,
        ConfigModel model
    )
    {
        var schema = model.Schema;
        var rootNamespace = TextUtil.PascalName(config.ProjectName());
        GenerateContract(batch, config.ConfigContractCsPath(root), model, rootNamespace);
        GenerateCodec(batch, config.ConfigCodecCsPath(root), schema, rootNamespace, model.SchemaHash);
    }

    private static void GenerateContract(
        GenerationBatch batch,
        string output,
        ConfigModel model,
        string rootNamespace
    )
    {
        var messages = model.Messages
            .OrderBy(item => item.Name == "GameConfig" ? "CoreConfig" : item.Name, StringComparer.Ordinal)
            .ToArray();

        var text = new StringBuilder();
        text.AppendLine("// @generated by fwgen config. Do not edit.");
        text.AppendLine("using System;");
        text.AppendLine("using System.Collections.Generic;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Core;");
        text.AppendLine();
        RenderConfigFields(text, model.FieldNames);
        text.AppendLine();
        RenderConfigPaths(text, model.Roots);
        text.AppendLine();
        foreach (var message in messages)
        {
            var className = message.Name == "GameConfig" ? "CoreConfig" : message.Name;
            text.AppendLine($"public sealed class {className}");
            text.AppendLine("{");
            foreach (var field in message.Fields)
            {
                if (field.IsRepeated)
                {
                    string itemType = CsConfigType(field.Type, false);
                    string name = Pascal(field.Name);
                    string backing = $"_field{field.Number}";
                    text.AppendLine($"    private IReadOnlyList<{itemType}> {backing} = global::System.Array.AsReadOnly(global::System.Array.Empty<{itemType}>());");
                    text.AppendLine($"    public IReadOnlyList<{itemType}> {name}");
                    text.AppendLine("    {");
                    text.AppendLine($"        get => {backing};");
                    text.AppendLine($"        init => {backing} = global::System.Array.AsReadOnly(new global::System.Collections.Generic.List<{itemType}>(value ?? throw new global::System.ArgumentNullException(nameof(value))).ToArray());");
                    text.AppendLine("    }");
                }
                else
                {
                    text.AppendLine($"    public {CsConfigType(field.Type, false)} {Pascal(field.Name)} {{ get; init; }}{CsConfigInit(field, model.Schema)}");
                }
            }
            text.AppendLine("}");
            text.AppendLine();
        }

        batch.StageText(output, text.ToString());
    }

    private static void RenderConfigPaths(StringBuilder text, IEnumerable<ConfigRoot> roots)
    {
        var orderedRoots = roots.OrderBy(item => item.Name, StringComparer.Ordinal).ToArray();

        text.AppendLine("public static class ConfigPath");
        text.AppendLine("{");
        foreach (var root in orderedRoots)
        {
            var name = Pascal(root.Name);
            text.AppendLine($"    public const string {name}Source = \"{EscapeCs(root.SourcePath)}\";");
            text.AppendLine($"    public const string {name}Pack = \"{EscapeCs(root.PackPath)}\";");
        }
        text.AppendLine();
        text.AppendLine("    public static IReadOnlyList<string> AllSourcePaths { get; } = global::System.Array.AsReadOnly(new string[]");
        text.AppendLine("    {");
        foreach (var root in orderedRoots)
        {
            text.AppendLine($"        {Pascal(root.Name)}Source,");
        }
        text.AppendLine("    });");
        text.AppendLine();
        text.AppendLine("    public static IReadOnlyList<string> AllPackPaths { get; } = global::System.Array.AsReadOnly(new string[]");
        text.AppendLine("    {");
        foreach (var root in orderedRoots)
        {
            text.AppendLine($"        {Pascal(root.Name)}Pack,");
        }
        text.AppendLine("    });");
        text.AppendLine("}");
    }

    private static void GenerateCodec(
        GenerationBatch batch,
        string output,
        ProtoSchema schema,
        string rootNamespace,
        string schemaHash
    )
    {
        var rowMessages = schema.Messages.Values
            .Where(item => item.Name.EndsWith("Config", StringComparison.Ordinal))
            .Where(item => CanGenerateRowReader(item, schema))
            .OrderBy(item => item.Name, StringComparer.Ordinal)
            .ToArray();
        var packMessages = schema.Messages.Values
            .Where(item => item.Name != "Fixed32")
            .OrderBy(item => item.Name.EndsWith("Config", StringComparison.Ordinal) ? 1 : 0)
            .ThenBy(item => item.Name, StringComparer.Ordinal)
            .ToArray();

        var text = new StringBuilder();
        text.AppendLine("// @generated by fwgen config. Do not edit.");
        text.AppendLine("using System;");
        text.AppendLine("using System.Collections.Generic;");
        text.AppendLine("using Fw.Rt.Config;");
        text.AppendLine("using System.Globalization;");
        text.AppendLine("using System.Text;");
        text.AppendLine("using System.Text.Json;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Core;");
        text.AppendLine();
        text.AppendLine("public static class ConfigCodec");
        text.AppendLine("{");
        RenderConfigRowReaders(text, rowMessages);
        RenderConfigPackReaders(text, schema, packMessages, schemaHash);
        RenderConfigCsvRuntime(text);
        text.AppendLine("}");
        batch.StageText(output, text.ToString());
    }

    private static void RenderConfigFields(StringBuilder text, IEnumerable<string> fields)
    {
        text.AppendLine("public static class ConfigField");
        text.AppendLine("{");
        foreach (var field in fields)
        {
            text.AppendLine($"    public const string {Pascal(field)} = \"{field}\";");
        }
        text.AppendLine("}");
    }

    private static string CsConfigType(string type, bool repeated)
    {
        var itemType = type switch
        {
            "string" => "string",
            "bool" => "bool",
            "float" => "float",
            "double" or "Fixed32" => "double",
            "uint32" => "uint",
            "uint64" => "ulong",
            "int32" or "sint32" => "int",
            "int64" or "sint64" => "long",
            _ => type == "GameConfig" ? "CoreConfig" : type,
        };
        return repeated ? $"IReadOnlyList<{itemType}>" : itemType;
    }

    private static string CsConfigInit(ProtoField field, ProtoSchema schema)
    {
        if (field.IsRepeated)
        {
            return " = new();";
        }
        if (field.Type == "string")
        {
            return " = \"\";";
        }
        if (schema.Messages.ContainsKey(field.Type) && field.Type != "Fixed32")
        {
            return " = new();";
        }
        return "";
    }

    private static bool CanGenerateRowReader(ProtoMessage message, ProtoSchema schema)
    {
        return message.Fields.All(field => !field.IsRepeated && IsConfigScalar(field.Type, schema));
    }

    private static bool IsConfigScalar(string type, ProtoSchema schema)
    {
        return type is "string" or "bool" or "float" or "double" or "Fixed32"
            or "uint32" or "uint64" or "int32" or "sint32" or "int64" or "sint64"
            || !schema.Messages.ContainsKey(type);
    }

    private static void RenderConfigRowReaders(StringBuilder text, IEnumerable<ProtoMessage> messages)
    {
        foreach (var message in messages)
        {
            var className = message.Name == "GameConfig" ? "CoreConfig" : message.Name;
            text.AppendLine($"    public static {className} Read{className}(Dictionary<string, string>? row)");
            text.AppendLine("    {");
            text.AppendLine($"        return new {className}");
            text.AppendLine("        {");
            foreach (var field in message.Fields)
            {
                text.AppendLine($"            {Pascal(field.Name)} = {ConfigReadExpr(field)},");
            }
            text.AppendLine("        };");
            text.AppendLine("    }");
            text.AppendLine();
        }
    }

    private static string ConfigReadExpr(ProtoField field)
    {
        var fieldName = $"ConfigField.{Pascal(field.Name)}";
        return field.Type switch
        {
            "string" => $"ReadString(row, {fieldName}, \"\")",
            "bool" => $"ReadBool(row, {fieldName}, false)",
            "float" => $"ReadFloat(row, {fieldName}, 0.0f)",
            "Fixed32" => $"ReadFixed(row, {fieldName}, 0.0)",
            "double" => $"ReadDouble(row, {fieldName}, 0.0)",
            "uint32" => $"ReadUInt(row, {fieldName}, 0)",
            "uint64" => $"ReadULong(row, {fieldName}, 0)",
            "int64" or "sint64" => $"ReadLong(row, {fieldName}, 0)",
            _ => $"ReadInt(row, {fieldName}, 0)",
        };
    }

    private static void RenderConfigPackReaders(
        StringBuilder text,
        ProtoSchema schema,
        IEnumerable<ProtoMessage> messages,
        string schemaHash
    )
    {
        var items = messages.ToArray();
        foreach (var message in items.Where(item => item.Name.EndsWith("Config", StringComparison.Ordinal)))
        {
            var className = ConfigClassName(message.Name);
            var rootName = TextUtil.Snake(message.Name[..^"Config".Length]);
            text.AppendLine($"    public static {className} Read{className}Pack(string key)");
            text.AppendLine("    {");
            text.AppendLine($"        JsonElement? value = ReadPackValue(ConfigPath.{Pascal(rootName)}Pack, key);");
            text.AppendLine($"        return value.HasValue ? Parse{className}Pack(value.Value) : new {className}();");
            text.AppendLine("    }");
            text.AppendLine();
        }

        foreach (var message in items)
        {
            RenderConfigPackParser(text, schema, message);
        }

        RenderConfigPackRuntime(text, schemaHash);
    }

    private static void RenderConfigPackParser(
        StringBuilder text,
        ProtoSchema schema,
        ProtoMessage message
    )
    {
        var className = ConfigClassName(message.Name);
        text.AppendLine($"    private static {className} Parse{className}Pack(JsonElement obj)");
        text.AppendLine("    {");
        text.AppendLine("        if (obj.ValueKind != JsonValueKind.Object)");
        text.AppendLine("        {");
        text.AppendLine($"            return new {className}();");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine($"        return new {className}");
        text.AppendLine("        {");
        foreach (var field in message.Fields)
        {
            text.AppendLine($"            {Pascal(field.Name)} = {ConfigPackExpr(field, schema)},");
        }
        text.AppendLine("        };");
        text.AppendLine("    }");
        text.AppendLine();
    }

    private static string ConfigPackExpr(ProtoField field, ProtoSchema schema)
    {
        var fieldName = $"ConfigField.{Pascal(field.Name)}";
        if (field.IsRepeated)
        {
            return IsMessageType(field.Type, schema) && field.Type != "Fixed32"
                ? $"ReadPackArray(obj, {fieldName}, Parse{ConfigClassName(field.Type)}Pack)"
                : $"ReadPackScalarArray<{CsConfigType(field.Type, false)}>(obj, {fieldName}, {ConfigPackScalarParser(field.Type)})";
        }

        if (IsMessageType(field.Type, schema) && field.Type != "Fixed32")
        {
            if (IsConfigMessage(field.Type))
            {
                var rootName = ConfigRootName(field.Type);
                return $"ReadPackConfigRef(obj, {fieldName}, ConfigPath.{Pascal(rootName)}Pack, Parse{ConfigClassName(field.Type)}Pack)";
            }
            return $"ReadPackMessage(obj, {fieldName}, Parse{ConfigClassName(field.Type)}Pack)";
        }

        return field.Type switch
        {
            "string" => $"ReadPackString(obj, {fieldName}, \"\")",
            "bool" => $"ReadPackBool(obj, {fieldName}, false)",
            "float" => $"ReadPackFloat(obj, {fieldName}, 0.0f)",
            "double" => $"ReadPackDouble(obj, {fieldName}, 0.0)",
            "uint32" => $"ReadPackUInt(obj, {fieldName}, 0)",
            "Fixed32" => $"ReadPackFixed(obj, {fieldName}, 0.0)",
            "uint64" => $"ReadPackULong(obj, {fieldName}, 0)",
            "int64" or "sint64" => $"ReadPackLong(obj, {fieldName}, 0)",
            _ => $"ReadPackInt(obj, {fieldName}, 0)",
        };
    }

    private static string ConfigPackScalarParser(string type)
    {
        return type switch
        {
            "string" => "value => ReadPackStringItem(value, \"\")",
            "bool" => "value => ReadPackBoolItem(value, false)",
            "float" => "value => ReadPackFloatItem(value, 0.0f)",
            "double" => "value => ReadPackDoubleItem(value, 0.0)",
            "uint32" => "value => ReadPackUIntItem(value, 0)",
            "Fixed32" => "value => ReadPackFixedItem(value, 0.0)",
            "uint64" => "value => ReadPackULongItem(value, 0)",
            "int64" or "sint64" => "value => ReadPackLongItem(value, 0)",
            _ => "value => ReadPackIntItem(value, 0)",
        };
    }

    private static void RenderConfigPackRuntime(StringBuilder text, string schemaHash)
    {
        text.AppendLine($"    private const string PackSchemaHash = \"{schemaHash}\";");
        text.AppendLine("    private static readonly object PackGate = new();");
        text.AppendLine("    private static readonly Dictionary<string, Dictionary<string, JsonElement>> PackCache = new(StringComparer.Ordinal);");
        text.AppendLine();
        text.AppendLine("    public static void ClearPackCache()");
        text.AppendLine("    {");
        text.AppendLine("        lock (PackGate)");
        text.AppendLine("        {");
        text.AppendLine("            PackCache.Clear();");
        text.AppendLine("        }");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static JsonElement? ReadPackValue(string path, string key)");
        text.AppendLine("    {");
        text.AppendLine("        Dictionary<string, JsonElement> entries = ReadPack(path);");
        text.AppendLine("        return entries.TryGetValue(key, out JsonElement value) ? value : null;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static List<string> ReadPackKeys(string path)");
        text.AppendLine("    {");
        text.AppendLine("        return new List<string>(ReadPack(path).Keys);");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static Dictionary<string, JsonElement> ReadPack(string path)");
        text.AppendLine("    {");
        text.AppendLine("        lock (PackGate)");
        text.AppendLine("        {");
        text.AppendLine("            if (PackCache.TryGetValue(path, out Dictionary<string, JsonElement>? cached))");
        text.AppendLine("            {");
        text.AppendLine("                return cached;");
        text.AppendLine("            }");
        text.AppendLine();
        text.AppendLine("            Dictionary<string, JsonElement> loaded = LoadPack(path);");
        text.AppendLine("            PackCache[path] = loaded;");
        text.AppendLine("            return loaded;");
        text.AppendLine("        }");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static Dictionary<string, JsonElement> LoadPack(string path)");
        text.AppendLine("    {");
        text.AppendLine("        byte[] bytes = Godot.FileAccess.GetFileAsBytes(path);");
        text.AppendLine("        try");
        text.AppendLine("        {");
        text.AppendLine("            return ConfigPack.Decode(bytes, PackSchemaHash);");
        text.AppendLine("        }");
        text.AppendLine("        catch (System.IO.InvalidDataException error)");
        text.AppendLine("        {");
        text.AppendLine("            throw new System.IO.InvalidDataException($\"failed to read config pack `{path}`: {error.Message}\", error);");
        text.AppendLine("        }");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static T ReadPackConfigRef<T>(JsonElement obj, string field, string path, Func<JsonElement, T> parser) where T : new()");
        text.AppendLine("    {");
        text.AppendLine("        if (!obj.TryGetProperty(field, out JsonElement value))");
        text.AppendLine("        {");
        text.AppendLine("            return new T();");
        text.AppendLine("        }");
        text.AppendLine("        if (value.ValueKind == JsonValueKind.String)");
        text.AppendLine("        {");
        text.AppendLine("            JsonElement? packed = ReadPackValue(path, value.GetString() ?? \"default\");");
        text.AppendLine("            return packed.HasValue ? parser(packed.Value) : new T();");
        text.AppendLine("        }");
        text.AppendLine("        return value.ValueKind == JsonValueKind.Object ? parser(value) : new T();");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static T ReadPackMessage<T>(JsonElement obj, string field, Func<JsonElement, T> parser) where T : new()");
        text.AppendLine("    {");
        text.AppendLine("        return obj.TryGetProperty(field, out JsonElement value) && value.ValueKind == JsonValueKind.Object");
        text.AppendLine("            ? parser(value)");
        text.AppendLine("            : new T();");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static List<T> ReadPackArray<T>(JsonElement obj, string field, Func<JsonElement, T> parser)");
        text.AppendLine("    {");
        text.AppendLine("        var output = new List<T>();");
        text.AppendLine("        if (!obj.TryGetProperty(field, out JsonElement value))");
        text.AppendLine("        {");
        text.AppendLine("            return output;");
        text.AppendLine("        }");
        text.AppendLine("        if (value.ValueKind != JsonValueKind.Array) throw new global::System.IO.InvalidDataException($\"config {field} must be an array\");");
        text.AppendLine("        foreach (JsonElement item in value.EnumerateArray())");
        text.AppendLine("        {");
        text.AppendLine("            output.Add(parser(item));");
        text.AppendLine("        }");
        text.AppendLine("        return output;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static List<T> ReadPackScalarArray<T>(JsonElement obj, string field, Func<JsonElement, T> parser)");
        text.AppendLine("    {");
        text.AppendLine("        var output = new List<T>();");
        text.AppendLine("        if (!obj.TryGetProperty(field, out JsonElement value))");
        text.AppendLine("        {");
        text.AppendLine("            return output;");
        text.AppendLine("        }");
        text.AppendLine("        if (value.ValueKind != JsonValueKind.Array) throw new global::System.IO.InvalidDataException($\"config {field} must be an array\");");
        text.AppendLine("        foreach (JsonElement item in value.EnumerateArray())");
        text.AppendLine("        {");
        text.AppendLine("            output.Add(parser(item));");
        text.AppendLine("        }");
        text.AppendLine("        return output;");
        text.AppendLine("    }");
        text.AppendLine();
        RenderConfigNumericRuntime(text);
        text.AppendLine("    private static double ReadPackFixed(JsonElement obj, string field, double fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return obj.TryGetProperty(field, out JsonElement value) ? ReadPackFixedItem(value, fallback) : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static bool ReadPackBool(JsonElement obj, string field, bool fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return obj.TryGetProperty(field, out JsonElement value) ? ReadPackBoolItem(value, fallback) : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static string ReadPackString(JsonElement obj, string field, string fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return obj.TryGetProperty(field, out JsonElement value) ? ReadPackStringItem(value, fallback) : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static double ReadPackFixedItem(JsonElement value, double fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return ReadPackIntItem(value, 0) / 256.0;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static bool ReadPackBoolItem(JsonElement value, bool fallback)");
        text.AppendLine("    {");
        text.AppendLine("        if (value.ValueKind == JsonValueKind.True)");
        text.AppendLine("        {");
        text.AppendLine("            return true;");
        text.AppendLine("        }");
        text.AppendLine("        if (value.ValueKind == JsonValueKind.False)");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");
        text.AppendLine("        return value.ValueKind == JsonValueKind.String ? ReadBool(new Dictionary<string, string> { [\"_\"] = value.GetString() ?? \"\" }, \"_\", fallback) : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static string ReadPackStringItem(JsonElement value, string fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return value.ValueKind == JsonValueKind.String ? value.GetString() ?? fallback : value.ToString();");
        text.AppendLine("    }");
        text.AppendLine();
    }

    private static void RenderConfigNumericRuntime(StringBuilder text)
    {
        text.AppendLine("""
    // Normalize only decimal placement; retain all significant digits before IEEE parsing.
    private static string NormalizeNumericDecimal(string raw)
    {
        var match = global::System.Text.RegularExpressions.Regex.Match(
            raw.Trim(' ', '\t', '\r', '\n', '\v', '\f'),
            @"\A([+-]?)([0-9]*)(?:\.([0-9]*))?(?:[eE]([+-]?[0-9]+))?\z"
        );
        if (!match.Success || match.Groups[2].Length + match.Groups[3].Length == 0)
            throw new global::System.IO.InvalidDataException("invalid finite decimal config text");
        string sign = match.Groups[1].Value;
        string digits = (match.Groups[2].Value + match.Groups[3].Value).TrimStart('0');
        if (digits.Length == 0) return sign + "0";
        string exponentText = match.Groups[4].Value;
        long exponent = 0;
        if (exponentText.Length != 0 && !long.TryParse(exponentText, NumberStyles.Integer, CultureInfo.InvariantCulture, out exponent))
            exponent = exponentText.StartsWith('-') ? -100000 : 100000;
        exponent = global::System.Math.Clamp(exponent, -100000, 100000) - match.Groups[3].Length + digits.Length - 1;
        return sign + digits[0] + "." + digits[1..] + "e" + exponent.ToString(CultureInfo.InvariantCulture);
    }
""");
        text.AppendLine("    public static double ReadFixed(Dictionary<string, string>? row, string field, double fallback)");
        text.AppendLine("    {");
        text.AppendLine("        if (row == null || !row.TryGetValue(field, out string? value) || string.IsNullOrWhiteSpace(value)) return fallback;");
        text.AppendLine("        double scaled = global::System.Math.Round(ParseDouble(value) * 256.0, global::System.MidpointRounding.AwayFromZero);");
        text.AppendLine("        if (!double.IsFinite(scaled) || scaled < int.MinValue || scaled > int.MaxValue) throw new global::System.IO.InvalidDataException(\"Fixed32 value is outside Q24.8 range\");");
        text.AppendLine("        return (int)scaled / 256.0;");
        text.AppendLine("    }");
        foreach (var (name, type, style, wide) in new[]
        {
            ("Int", "int", "Integer", false), ("UInt", "uint", "Integer", false),
            ("Long", "long", "Integer", true), ("ULong", "ulong", "Integer", true),
            ("Float", "float", "Float", false), ("Double", "double", "Float", false),
        })
        {
            string finite = style == "Float" ? $" && {type}.IsFinite(parsed)" : "";
            text.AppendLine($"    private static {type} Parse{name}(string text)");
            text.AppendLine("    {");
            text.AppendLine("        if (text.Length > 4096) throw new global::System.IO.InvalidDataException(\"config numeric text exceeds 4096 characters\");");
            if (style == "Float")
            {
                text.AppendLine("        text = NormalizeNumericDecimal(text);");
            }
            text.AppendLine($"        return {type}.TryParse(text, NumberStyles.{style}, CultureInfo.InvariantCulture, out {type} parsed){finite}");
            text.AppendLine("            ? parsed");
            text.AppendLine($"            : throw new global::System.IO.InvalidDataException($\"config value must be a finite {type} in its declared range: `{{text}}`\");");
            text.AppendLine("    }");
            text.AppendLine($"    public static {type} Read{name}(Dictionary<string, string>? row, string field, {type} fallback)");
            text.AppendLine("    {");
            text.AppendLine($"        return row != null && row.TryGetValue(field, out string? value) && !string.IsNullOrWhiteSpace(value) ? Parse{name}(value) : fallback;");
            text.AppendLine("    }");
            text.AppendLine($"    private static {type} ReadPack{name}(JsonElement obj, string field, {type} fallback)");
            text.AppendLine("    {");
            text.AppendLine($"        return obj.TryGetProperty(field, out JsonElement value) ? ReadPack{name}Item(value, fallback) : fallback;");
            text.AppendLine("    }");
            text.AppendLine($"    private static {type} ReadPack{name}Item(JsonElement value, {type} fallback)");
            text.AppendLine("    {");
            if (wide)
            {
                text.AppendLine("        if (value.ValueKind == JsonValueKind.Number && (!value.TryGetInt64(out long integer) || integer < -9007199254740991L || integer > 9007199254740991L))");
                text.AppendLine("            throw new global::System.IO.InvalidDataException(\"64-bit JSON integers outside the safe range must use decimal strings.\");");
            }
            text.AppendLine($"        return Parse{name}(value.ValueKind switch");
            text.AppendLine("        {");
            text.AppendLine("            JsonValueKind.String => value.GetString()!,");
            text.AppendLine("            JsonValueKind.Number => value.GetRawText(),");
            text.AppendLine("            _ => throw new global::System.IO.InvalidDataException(\"config numeric value must be a number or decimal text\"),");
            text.AppendLine("        });");
            text.AppendLine("    }");
            text.AppendLine();
        }
    }

    private static void RenderConfigCsvRuntime(StringBuilder text)
    {
        text.AppendLine("    public static Dictionary<string, string>? ReadRow(string path, string key)");
        text.AppendLine("    {");
        text.AppendLine("        string text = Godot.FileAccess.GetFileAsString(path);");
        text.AppendLine("        if (string.IsNullOrEmpty(text))");
        text.AppendLine("        {");
        text.AppendLine("            return null;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        string[] lines = text.Replace(\"\\r\\n\", \"\\n\").Replace('\\r', '\\n').Split('\\n');");
        text.AppendLine("        if (lines.Length == 0)");
        text.AppendLine("        {");
        text.AppendLine("            return null;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        string[] headers = SplitCsvLine(lines[0]);");
        text.AppendLine("        for (int lineIndex = 1; lineIndex < lines.Length; lineIndex += 1)");
        text.AppendLine("        {");
        text.AppendLine("            string line = lines[lineIndex].Trim();");
        text.AppendLine("            if (string.IsNullOrEmpty(line))");
        text.AppendLine("            {");
        text.AppendLine("                continue;");
        text.AppendLine("            }");
        text.AppendLine();
        text.AppendLine("            string[] values = SplitCsvLine(line);");
        text.AppendLine("            var row = new Dictionary<string, string>();");
        text.AppendLine("            for (int index = 0; index < System.Math.Min(headers.Length, values.Length); index += 1)");
        text.AppendLine("            {");
        text.AppendLine("                row[NormalizeHeader(headers[index], index)] = values[index];");
        text.AppendLine("            }");
        text.AppendLine();
        text.AppendLine("            if (row.TryGetValue(ConfigField.Key, out string? rowKey) && rowKey == key)");
        text.AppendLine("            {");
        text.AppendLine("                return row;");
        text.AppendLine("            }");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        return null;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static bool ReadBool(Dictionary<string, string>? row, string field, bool fallback)");
        text.AppendLine("    {");
        text.AppendLine("        if (row == null || !row.TryGetValue(field, out string? value))");
        text.AppendLine("        {");
        text.AppendLine("            return fallback;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        return value.ToLowerInvariant() switch");
        text.AppendLine("        {");
        text.AppendLine("            \"1\" or \"true\" or \"yes\" => true,");
        text.AppendLine("            \"0\" or \"false\" or \"no\" => false,");
        text.AppendLine("            _ => fallback,");
        text.AppendLine("        };");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static string ReadString(Dictionary<string, string>? row, string field, string fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return row != null && row.TryGetValue(field, out string? value) && !string.IsNullOrEmpty(value)");
        text.AppendLine("            ? value");
        text.AppendLine("            : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static string[] SplitCsvLine(string line)");
        text.AppendLine("    {");
        text.AppendLine("        var values = new List<string>();");
        text.AppendLine("        var current = new System.Text.StringBuilder();");
        text.AppendLine("        bool inQuote = false;");
        text.AppendLine("        for (int index = 0; index < line.Length; index += 1)");
        text.AppendLine("        {");
        text.AppendLine("            char ch = line[index];");
        text.AppendLine("            if (ch == '\"')");
        text.AppendLine("            {");
        text.AppendLine("                if (inQuote && index + 1 < line.Length && line[index + 1] == '\"')");
        text.AppendLine("                {");
        text.AppendLine("                    current.Append('\"');");
        text.AppendLine("                    index += 1;");
        text.AppendLine("                }");
        text.AppendLine("                else");
        text.AppendLine("                {");
        text.AppendLine("                    inQuote = !inQuote;");
        text.AppendLine("                }");
        text.AppendLine("                continue;");
        text.AppendLine("            }");
        text.AppendLine("            if (ch == ',' && !inQuote)");
        text.AppendLine("            {");
        text.AppendLine("                values.Add(current.ToString());");
        text.AppendLine("                current.Clear();");
        text.AppendLine("                continue;");
        text.AppendLine("            }");
        text.AppendLine("            current.Append(ch);");
        text.AppendLine("        }");
        text.AppendLine("        if (inQuote)");
        text.AppendLine("        {");
        text.AppendLine("            throw new System.IO.InvalidDataException(\"CSV line has an unclosed quoted field.\");");
        text.AppendLine("        }");
        text.AppendLine("        values.Add(current.ToString());");
        text.AppendLine("        return values.ToArray();");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static string NormalizeHeader(string header, int index)");
        text.AppendLine("    {");
        text.AppendLine("        return index == 0 && header.Length > 0 && header[0] == '\\ufeff'");
        text.AppendLine("            ? header[1..]");
        text.AppendLine("            : header;");
        text.AppendLine("    }");
    }

    private static string Pascal(string value)
    {
        return TextUtil.SchemaPascal(value);
    }

    private static string EscapeCs(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
