using System.Text;
using static ConfigSchema;

static class ConfigCs
{
    internal static void Stage(
        GenerationBatch batch,
        string root,
        FwConfig config,
        ConfigModel model
    )
    {
        var schema = model.Schema;
        var rootNamespace = TextUtil.PascalName(config.ProjectName());
        GenerateContract(batch, config.ConfigContractCsPath(root), model, rootNamespace);
        GenerateCodec(batch, config.ConfigCodecCsPath(root), schema, rootNamespace, model.SchemaHash);
    }

    private static void GenerateContract(
        GenerationBatch batch,
        string output,
        ConfigModel model,
        string rootNamespace
    )
    {
        var messages = model.Messages
            .OrderBy(item => item.Name == "GameConfig" ? "CoreConfig" : item.Name, StringComparer.Ordinal)
            .ToArray();

        var text = new StringBuilder();
        text.AppendLine("// @generated by fwgen config. Do not edit.");
        text.AppendLine("using System.Collections.Generic;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Core;");
        text.AppendLine();
        RenderConfigFields(text, model.FieldNames);
        text.AppendLine();
        RenderConfigPaths(text, model.Roots);
        text.AppendLine();
        foreach (var message in messages)
        {
            var className = message.Name == "GameConfig" ? "CoreConfig" : message.Name;
            text.AppendLine($"public sealed class {className}");
            text.AppendLine("{");
            foreach (var field in message.Fields)
            {
                text.AppendLine($"    public {CsConfigType(field.Type, field.IsRepeated)} {Pascal(field.Name)} {{ get; init; }}{CsConfigInit(field, model.Schema)}");
            }
            text.AppendLine("}");
            text.AppendLine();
        }

        batch.StageText(output, text.ToString());
    }

    private static void RenderConfigPaths(StringBuilder text, IEnumerable<ConfigRoot> roots)
    {
        var orderedRoots = roots.OrderBy(item => item.Name, StringComparer.Ordinal).ToArray();

        text.AppendLine("public static class ConfigPath");
        text.AppendLine("{");
        foreach (var root in orderedRoots)
        {
            var name = Pascal(root.Name);
            text.AppendLine($"    public const string {name}Source = \"{EscapeCs(root.SourcePath)}\";");
            text.AppendLine($"    public const string {name}Pack = \"{EscapeCs(root.PackPath)}\";");
        }
        text.AppendLine();
        text.AppendLine("    public static IReadOnlyList<string> AllSourcePaths { get; } = new[]");
        text.AppendLine("    {");
        foreach (var root in orderedRoots)
        {
            text.AppendLine($"        {Pascal(root.Name)}Source,");
        }
        text.AppendLine("    };");
        text.AppendLine();
        text.AppendLine("    public static IReadOnlyList<string> AllPackPaths { get; } = new[]");
        text.AppendLine("    {");
        foreach (var root in orderedRoots)
        {
            text.AppendLine($"        {Pascal(root.Name)}Pack,");
        }
        text.AppendLine("    };");
        text.AppendLine("}");
    }

    private static void GenerateCodec(
        GenerationBatch batch,
        string output,
        ProtoSchema schema,
        string rootNamespace,
        string schemaHash
    )
    {
        var rowMessages = schema.Messages.Values
            .Where(item => item.Name.EndsWith("Config", StringComparison.Ordinal))
            .Where(item => CanGenerateRowReader(item, schema))
            .OrderBy(item => item.Name, StringComparer.Ordinal)
            .ToArray();
        var packMessages = schema.Messages.Values
            .Where(item => item.Name != "Fixed32")
            .OrderBy(item => item.Name.EndsWith("Config", StringComparison.Ordinal) ? 1 : 0)
            .ThenBy(item => item.Name, StringComparer.Ordinal)
            .ToArray();

        var text = new StringBuilder();
        text.AppendLine("// @generated by fwgen config. Do not edit.");
        text.AppendLine("using System;");
        text.AppendLine("using System.Collections.Generic;");
        text.AppendLine("using Fw.Rt.Config;");
        text.AppendLine("using System.Globalization;");
        text.AppendLine("using System.Text;");
        text.AppendLine("using System.Text.Json;");
        text.AppendLine();
        text.AppendLine($"namespace {rootNamespace}.Core;");
        text.AppendLine();
        text.AppendLine("public static class ConfigCodec");
        text.AppendLine("{");
        RenderConfigRowReaders(text, rowMessages);
        RenderConfigPackReaders(text, schema, packMessages, schemaHash);
        RenderConfigCsvRuntime(text);
        text.AppendLine("}");
        batch.StageText(output, text.ToString());
    }

    private static void RenderConfigFields(StringBuilder text, IEnumerable<string> fields)
    {
        text.AppendLine("public static class ConfigField");
        text.AppendLine("{");
        foreach (var field in fields)
        {
            text.AppendLine($"    public const string {Pascal(field)} = \"{field}\";");
        }
        text.AppendLine("}");
    }

    private static string CsConfigType(string type, bool repeated)
    {
        var itemType = type switch
        {
            "string" => "string",
            "bool" => "bool",
            "float" or "double" or "Fixed32" => "float",
            "uint32" => "int",
            "uint64" => "ulong",
            "int32" or "sint32" => "int",
            "int64" or "sint64" => "long",
            _ => type == "GameConfig" ? "CoreConfig" : type,
        };
        return repeated ? $"List<{itemType}>" : itemType;
    }

    private static string CsConfigInit(ProtoField field, ProtoSchema schema)
    {
        if (field.IsRepeated)
        {
            return " = new();";
        }
        if (field.Type == "string")
        {
            return " = \"\";";
        }
        if (schema.Messages.ContainsKey(field.Type) && field.Type != "Fixed32")
        {
            return " = new();";
        }
        return "";
    }

    private static bool CanGenerateRowReader(ProtoMessage message, ProtoSchema schema)
    {
        return message.Fields.All(field => !field.IsRepeated && IsConfigScalar(field.Type, schema));
    }

    private static bool IsConfigScalar(string type, ProtoSchema schema)
    {
        return type is "string" or "bool" or "float" or "double" or "Fixed32"
            or "uint32" or "uint64" or "int32" or "sint32" or "int64" or "sint64"
            || !schema.Messages.ContainsKey(type);
    }

    private static void RenderConfigRowReaders(StringBuilder text, IEnumerable<ProtoMessage> messages)
    {
        foreach (var message in messages)
        {
            var className = message.Name == "GameConfig" ? "CoreConfig" : message.Name;
            text.AppendLine($"    public static {className} Read{className}(Dictionary<string, string>? row)");
            text.AppendLine("    {");
            text.AppendLine($"        return new {className}");
            text.AppendLine("        {");
            foreach (var field in message.Fields)
            {
                text.AppendLine($"            {Pascal(field.Name)} = {ConfigReadExpr(field)},");
            }
            text.AppendLine("        };");
            text.AppendLine("    }");
            text.AppendLine();
        }
    }

    private static string ConfigReadExpr(ProtoField field)
    {
        var fieldName = $"ConfigField.{Pascal(field.Name)}";
        return field.Type switch
        {
            "string" => $"ReadString(row, {fieldName}, \"\")",
            "bool" => $"ReadBool(row, {fieldName}, false)",
            "float" or "double" or "Fixed32" => $"ReadFloat(row, {fieldName}, 0.0f)",
            "uint64" => $"ReadULong(row, {fieldName}, 0)",
            "int64" or "sint64" => $"ReadLong(row, {fieldName}, 0)",
            _ => $"ReadInt(row, {fieldName}, 0)",
        };
    }

    private static void RenderConfigPackReaders(
        StringBuilder text,
        ProtoSchema schema,
        IEnumerable<ProtoMessage> messages,
        string schemaHash
    )
    {
        var items = messages.ToArray();
        foreach (var message in items.Where(item => item.Name.EndsWith("Config", StringComparison.Ordinal)))
        {
            var className = ConfigClassName(message.Name);
            var rootName = TextUtil.Snake(message.Name[..^"Config".Length]);
            text.AppendLine($"    public static {className} Read{className}Pack(string key)");
            text.AppendLine("    {");
            text.AppendLine($"        JsonElement? value = ReadPackValue(ConfigPath.{Pascal(rootName)}Pack, key);");
            text.AppendLine($"        return value.HasValue ? Parse{className}Pack(value.Value) : new {className}();");
            text.AppendLine("    }");
            text.AppendLine();
        }

        foreach (var message in items)
        {
            RenderConfigPackParser(text, schema, message);
        }

        RenderConfigPackRuntime(text, schemaHash);
    }

    private static void RenderConfigPackParser(
        StringBuilder text,
        ProtoSchema schema,
        ProtoMessage message
    )
    {
        var className = ConfigClassName(message.Name);
        text.AppendLine($"    private static {className} Parse{className}Pack(JsonElement obj)");
        text.AppendLine("    {");
        text.AppendLine("        if (obj.ValueKind != JsonValueKind.Object)");
        text.AppendLine("        {");
        text.AppendLine($"            return new {className}();");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine($"        return new {className}");
        text.AppendLine("        {");
        foreach (var field in message.Fields)
        {
            text.AppendLine($"            {Pascal(field.Name)} = {ConfigPackExpr(field, schema)},");
        }
        text.AppendLine("        };");
        text.AppendLine("    }");
        text.AppendLine();
    }

    private static string ConfigPackExpr(ProtoField field, ProtoSchema schema)
    {
        var fieldName = $"ConfigField.{Pascal(field.Name)}";
        if (field.IsRepeated)
        {
            return IsMessageType(field.Type, schema) && field.Type != "Fixed32"
                ? $"ReadPackArray(obj, {fieldName}, Parse{ConfigClassName(field.Type)}Pack)"
                : $"ReadPackScalarArray<{CsConfigType(field.Type, false)}>(obj, {fieldName}, {ConfigPackScalarParser(field.Type)})";
        }

        if (IsMessageType(field.Type, schema) && field.Type != "Fixed32")
        {
            if (IsConfigMessage(field.Type))
            {
                var rootName = ConfigRootName(field.Type);
                return $"ReadPackConfigRef(obj, {fieldName}, ConfigPath.{Pascal(rootName)}Pack, Parse{ConfigClassName(field.Type)}Pack)";
            }
            return $"ReadPackMessage(obj, {fieldName}, Parse{ConfigClassName(field.Type)}Pack)";
        }

        return field.Type switch
        {
            "string" => $"ReadPackString(obj, {fieldName}, \"\")",
            "bool" => $"ReadPackBool(obj, {fieldName}, false)",
            "float" or "double" => $"ReadPackFloat(obj, {fieldName}, 0.0f)",
            "Fixed32" => $"ReadPackFixed(obj, {fieldName}, 0.0f)",
            "uint64" => $"ReadPackULong(obj, {fieldName}, 0)",
            "int64" or "sint64" => $"ReadPackLong(obj, {fieldName}, 0)",
            _ => $"ReadPackInt(obj, {fieldName}, 0)",
        };
    }

    private static string ConfigPackScalarParser(string type)
    {
        return type switch
        {
            "string" => "value => ReadPackStringItem(value, \"\")",
            "bool" => "value => ReadPackBoolItem(value, false)",
            "float" or "double" => "value => ReadPackFloatItem(value, 0.0f)",
            "Fixed32" => "value => ReadPackFixedItem(value, 0.0f)",
            "uint64" => "value => ReadPackULongItem(value, 0)",
            "int64" or "sint64" => "value => ReadPackLongItem(value, 0)",
            _ => "value => ReadPackIntItem(value, 0)",
        };
    }

    private static void RenderConfigPackRuntime(StringBuilder text, string schemaHash)
    {
        text.AppendLine($"    private const string PackSchemaHash = \"{schemaHash}\";");
        text.AppendLine("    private static readonly object PackGate = new();");
        text.AppendLine("    private static readonly Dictionary<string, Dictionary<string, JsonElement>> PackCache = new(StringComparer.Ordinal);");
        text.AppendLine();
        text.AppendLine("    public static void ClearPackCache()");
        text.AppendLine("    {");
        text.AppendLine("        lock (PackGate)");
        text.AppendLine("        {");
        text.AppendLine("            PackCache.Clear();");
        text.AppendLine("        }");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static JsonElement? ReadPackValue(string path, string key)");
        text.AppendLine("    {");
        text.AppendLine("        Dictionary<string, JsonElement> entries = ReadPack(path);");
        text.AppendLine("        return entries.TryGetValue(key, out JsonElement value) ? value : null;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static List<string> ReadPackKeys(string path)");
        text.AppendLine("    {");
        text.AppendLine("        return new List<string>(ReadPack(path).Keys);");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static Dictionary<string, JsonElement> ReadPack(string path)");
        text.AppendLine("    {");
        text.AppendLine("        lock (PackGate)");
        text.AppendLine("        {");
        text.AppendLine("            if (PackCache.TryGetValue(path, out Dictionary<string, JsonElement>? cached))");
        text.AppendLine("            {");
        text.AppendLine("                return cached;");
        text.AppendLine("            }");
        text.AppendLine();
        text.AppendLine("            Dictionary<string, JsonElement> loaded = LoadPack(path);");
        text.AppendLine("            PackCache[path] = loaded;");
        text.AppendLine("            return loaded;");
        text.AppendLine("        }");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static Dictionary<string, JsonElement> LoadPack(string path)");
        text.AppendLine("    {");
        text.AppendLine("        byte[] bytes = Godot.FileAccess.GetFileAsBytes(path);");
        text.AppendLine("        try");
        text.AppendLine("        {");
        text.AppendLine("            return ConfigPack.Decode(bytes, PackSchemaHash);");
        text.AppendLine("        }");
        text.AppendLine("        catch (System.IO.InvalidDataException error)");
        text.AppendLine("        {");
        text.AppendLine("            throw new System.IO.InvalidDataException($\"failed to read config pack `{path}`: {error.Message}\", error);");
        text.AppendLine("        }");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static T ReadPackConfigRef<T>(JsonElement obj, string field, string path, Func<JsonElement, T> parser) where T : new()");
        text.AppendLine("    {");
        text.AppendLine("        if (!obj.TryGetProperty(field, out JsonElement value))");
        text.AppendLine("        {");
        text.AppendLine("            return new T();");
        text.AppendLine("        }");
        text.AppendLine("        if (value.ValueKind == JsonValueKind.String)");
        text.AppendLine("        {");
        text.AppendLine("            JsonElement? packed = ReadPackValue(path, value.GetString() ?? \"default\");");
        text.AppendLine("            return packed.HasValue ? parser(packed.Value) : new T();");
        text.AppendLine("        }");
        text.AppendLine("        return value.ValueKind == JsonValueKind.Object ? parser(value) : new T();");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static T ReadPackMessage<T>(JsonElement obj, string field, Func<JsonElement, T> parser) where T : new()");
        text.AppendLine("    {");
        text.AppendLine("        return obj.TryGetProperty(field, out JsonElement value) && value.ValueKind == JsonValueKind.Object");
        text.AppendLine("            ? parser(value)");
        text.AppendLine("            : new T();");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static List<T> ReadPackArray<T>(JsonElement obj, string field, Func<JsonElement, T> parser)");
        text.AppendLine("    {");
        text.AppendLine("        var output = new List<T>();");
        text.AppendLine("        if (!obj.TryGetProperty(field, out JsonElement value) || value.ValueKind != JsonValueKind.Array)");
        text.AppendLine("        {");
        text.AppendLine("            return output;");
        text.AppendLine("        }");
        text.AppendLine("        foreach (JsonElement item in value.EnumerateArray())");
        text.AppendLine("        {");
        text.AppendLine("            output.Add(parser(item));");
        text.AppendLine("        }");
        text.AppendLine("        return output;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static List<T> ReadPackScalarArray<T>(JsonElement obj, string field, Func<JsonElement, T> parser)");
        text.AppendLine("    {");
        text.AppendLine("        var output = new List<T>();");
        text.AppendLine("        if (!obj.TryGetProperty(field, out JsonElement value) || value.ValueKind != JsonValueKind.Array)");
        text.AppendLine("        {");
        text.AppendLine("            return output;");
        text.AppendLine("        }");
        text.AppendLine("        foreach (JsonElement item in value.EnumerateArray())");
        text.AppendLine("        {");
        text.AppendLine("            output.Add(parser(item));");
        text.AppendLine("        }");
        text.AppendLine("        return output;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static int ReadPackInt(JsonElement obj, string field, int fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return obj.TryGetProperty(field, out JsonElement value) ? ReadPackIntItem(value, fallback) : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static long ReadPackLong(JsonElement obj, string field, long fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return obj.TryGetProperty(field, out JsonElement value) ? ReadPackLongItem(value, fallback) : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static ulong ReadPackULong(JsonElement obj, string field, ulong fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return obj.TryGetProperty(field, out JsonElement value) ? ReadPackULongItem(value, fallback) : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static float ReadPackFloat(JsonElement obj, string field, float fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return obj.TryGetProperty(field, out JsonElement value) ? ReadPackFloatItem(value, fallback) : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static float ReadPackFixed(JsonElement obj, string field, float fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return obj.TryGetProperty(field, out JsonElement value) ? ReadPackFixedItem(value, fallback) : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static bool ReadPackBool(JsonElement obj, string field, bool fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return obj.TryGetProperty(field, out JsonElement value) ? ReadPackBoolItem(value, fallback) : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static string ReadPackString(JsonElement obj, string field, string fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return obj.TryGetProperty(field, out JsonElement value) ? ReadPackStringItem(value, fallback) : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static int ReadPackIntItem(JsonElement value, int fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out int number)");
        text.AppendLine("            ? number");
        text.AppendLine("            : value.ValueKind == JsonValueKind.String && int.TryParse(value.GetString(), out int parsed) ? parsed : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static long ReadPackLongItem(JsonElement value, long fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return value.ValueKind == JsonValueKind.Number && value.TryGetInt64(out long number)");
        text.AppendLine("            ? number");
        text.AppendLine("            : value.ValueKind == JsonValueKind.String && long.TryParse(value.GetString(), out long parsed) ? parsed : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static ulong ReadPackULongItem(JsonElement value, ulong fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return value.ValueKind == JsonValueKind.Number && value.TryGetUInt64(out ulong number)");
        text.AppendLine("            ? number");
        text.AppendLine("            : value.ValueKind == JsonValueKind.String && ulong.TryParse(value.GetString(), out ulong parsed) ? parsed : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static float ReadPackFloatItem(JsonElement value, float fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return value.ValueKind == JsonValueKind.Number && value.TryGetSingle(out float number)");
        text.AppendLine("            ? number");
        text.AppendLine("            : value.ValueKind == JsonValueKind.String && float.TryParse(value.GetString(), NumberStyles.Float, CultureInfo.InvariantCulture, out float parsed) ? parsed : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static float ReadPackFixedItem(JsonElement value, float fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return ReadPackFloatItem(value, fallback * 256.0f) / 256.0f;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static bool ReadPackBoolItem(JsonElement value, bool fallback)");
        text.AppendLine("    {");
        text.AppendLine("        if (value.ValueKind == JsonValueKind.True)");
        text.AppendLine("        {");
        text.AppendLine("            return true;");
        text.AppendLine("        }");
        text.AppendLine("        if (value.ValueKind == JsonValueKind.False)");
        text.AppendLine("        {");
        text.AppendLine("            return false;");
        text.AppendLine("        }");
        text.AppendLine("        return value.ValueKind == JsonValueKind.String ? ReadBool(new Dictionary<string, string> { [\"_\"] = value.GetString() ?? \"\" }, \"_\", fallback) : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static string ReadPackStringItem(JsonElement value, string fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return value.ValueKind == JsonValueKind.String ? value.GetString() ?? fallback : value.ToString();");
        text.AppendLine("    }");
        text.AppendLine();
    }

    private static void RenderConfigCsvRuntime(StringBuilder text)
    {
        text.AppendLine("    public static Dictionary<string, string>? ReadRow(string path, string key)");
        text.AppendLine("    {");
        text.AppendLine("        string text = Godot.FileAccess.GetFileAsString(path);");
        text.AppendLine("        if (string.IsNullOrEmpty(text))");
        text.AppendLine("        {");
        text.AppendLine("            return null;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        string[] lines = text.Replace(\"\\r\\n\", \"\\n\").Replace('\\r', '\\n').Split('\\n');");
        text.AppendLine("        if (lines.Length == 0)");
        text.AppendLine("        {");
        text.AppendLine("            return null;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        string[] headers = SplitCsvLine(lines[0]);");
        text.AppendLine("        for (int lineIndex = 1; lineIndex < lines.Length; lineIndex += 1)");
        text.AppendLine("        {");
        text.AppendLine("            string line = lines[lineIndex].Trim();");
        text.AppendLine("            if (string.IsNullOrEmpty(line))");
        text.AppendLine("            {");
        text.AppendLine("                continue;");
        text.AppendLine("            }");
        text.AppendLine();
        text.AppendLine("            string[] values = SplitCsvLine(line);");
        text.AppendLine("            var row = new Dictionary<string, string>();");
        text.AppendLine("            for (int index = 0; index < System.Math.Min(headers.Length, values.Length); index += 1)");
        text.AppendLine("            {");
        text.AppendLine("                row[NormalizeHeader(headers[index], index)] = values[index];");
        text.AppendLine("            }");
        text.AppendLine();
        text.AppendLine("            if (row.TryGetValue(ConfigField.Key, out string? rowKey) && rowKey == key)");
        text.AppendLine("            {");
        text.AppendLine("                return row;");
        text.AppendLine("            }");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        return null;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static int ReadInt(Dictionary<string, string>? row, string field, int fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return row != null && row.TryGetValue(field, out string? value) && int.TryParse(value, out int parsed)");
        text.AppendLine("            ? parsed");
        text.AppendLine("            : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static long ReadLong(Dictionary<string, string>? row, string field, long fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return row != null && row.TryGetValue(field, out string? value) && long.TryParse(value, out long parsed)");
        text.AppendLine("            ? parsed");
        text.AppendLine("            : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static ulong ReadULong(Dictionary<string, string>? row, string field, ulong fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return row != null && row.TryGetValue(field, out string? value) && ulong.TryParse(value, out ulong parsed)");
        text.AppendLine("            ? parsed");
        text.AppendLine("            : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static float ReadFloat(Dictionary<string, string>? row, string field, float fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return row != null");
        text.AppendLine("            && row.TryGetValue(field, out string? value)");
        text.AppendLine("            && float.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out float parsed)");
        text.AppendLine("            ? parsed");
        text.AppendLine("            : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static bool ReadBool(Dictionary<string, string>? row, string field, bool fallback)");
        text.AppendLine("    {");
        text.AppendLine("        if (row == null || !row.TryGetValue(field, out string? value))");
        text.AppendLine("        {");
        text.AppendLine("            return fallback;");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        return value.ToLowerInvariant() switch");
        text.AppendLine("        {");
        text.AppendLine("            \"1\" or \"true\" or \"yes\" => true,");
        text.AppendLine("            \"0\" or \"false\" or \"no\" => false,");
        text.AppendLine("            _ => fallback,");
        text.AppendLine("        };");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    public static string ReadString(Dictionary<string, string>? row, string field, string fallback)");
        text.AppendLine("    {");
        text.AppendLine("        return row != null && row.TryGetValue(field, out string? value) && !string.IsNullOrEmpty(value)");
        text.AppendLine("            ? value");
        text.AppendLine("            : fallback;");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static string[] SplitCsvLine(string line)");
        text.AppendLine("    {");
        text.AppendLine("        var values = new List<string>();");
        text.AppendLine("        var current = new System.Text.StringBuilder();");
        text.AppendLine("        bool inQuote = false;");
        text.AppendLine("        for (int index = 0; index < line.Length; index += 1)");
        text.AppendLine("        {");
        text.AppendLine("            char ch = line[index];");
        text.AppendLine("            if (ch == '\"')");
        text.AppendLine("            {");
        text.AppendLine("                if (inQuote && index + 1 < line.Length && line[index + 1] == '\"')");
        text.AppendLine("                {");
        text.AppendLine("                    current.Append('\"');");
        text.AppendLine("                    index += 1;");
        text.AppendLine("                }");
        text.AppendLine("                else");
        text.AppendLine("                {");
        text.AppendLine("                    inQuote = !inQuote;");
        text.AppendLine("                }");
        text.AppendLine("                continue;");
        text.AppendLine("            }");
        text.AppendLine("            if (ch == ',' && !inQuote)");
        text.AppendLine("            {");
        text.AppendLine("                values.Add(current.ToString());");
        text.AppendLine("                current.Clear();");
        text.AppendLine("                continue;");
        text.AppendLine("            }");
        text.AppendLine("            current.Append(ch);");
        text.AppendLine("        }");
        text.AppendLine("        if (inQuote)");
        text.AppendLine("        {");
        text.AppendLine("            throw new System.IO.InvalidDataException(\"CSV line has an unclosed quoted field.\");");
        text.AppendLine("        }");
        text.AppendLine("        values.Add(current.ToString());");
        text.AppendLine("        return values.ToArray();");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    private static string NormalizeHeader(string header, int index)");
        text.AppendLine("    {");
        text.AppendLine("        return index == 0 && header.Length > 0 && header[0] == '\\ufeff'");
        text.AppendLine("            ? header[1..]");
        text.AppendLine("            : header;");
        text.AppendLine("    }");
    }

    private static string Pascal(string value)
    {
        return TextUtil.SchemaPascal(value);
    }

    private static string EscapeCs(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
